var searchData=
[
  ['шаг_201_3a_20авторизация_20кооператива_0',['Шаг 1: Авторизация кооператива',['../group__public__capital__configuration__process.html#autotoc_md2',1,'']]],
  ['шаг_201_3a_20добавление_20соавтора_20проекта_1',['Шаг 1: Добавление соавтора проекта',['../group__public__capital__add__author__process.html#autotoc_md161',1,'']]],
  ['шаг_201_3a_20завершение_20голосования_2',['Шаг 1: Завершение голосования',['../group__public__capital__voting__completion__process.html#autotoc_md163',1,'']]],
  ['шаг_201_3a_20инициация_20аллокации_20средств_3',['Шаг 1: Инициация аллокации средств',['../group__public__capital__allocate__process.html#autotoc_md111',1,'']]],
  ['шаг_201_3a_20инициация_20возврата_20неиспользованных_20средств_4',['Шаг 1: Инициация возврата неиспользованных средств',['../group__public__capital__unused__return__process.html#autotoc_md146',1,'']]],
  ['шаг_201_3a_20инициация_20голосования_5',['Шаг 1: Инициация голосования',['../group__public__capital__voting__start__process.html#autotoc_md216',1,'']]],
  ['шаг_201_3a_20инициация_20деаллокации_20средств_6',['Шаг 1: Инициация деаллокации средств',['../group__public__capital__diallocate__process.html#autotoc_md117',1,'']]],
  ['шаг_201_3a_20инициация_20запуска_20проекта_7',['Шаг 1: Инициация запуска проекта',['../group__public__capital__project__start__process.html#autotoc_md207',1,'']]],
  ['шаг_201_3a_20инициация_20назначения_20мастера_8',['Шаг 1: Инициация назначения мастера',['../group__public__capital__set__master__process.html#autotoc_md185',1,'']]],
  ['шаг_201_3a_20инициация_20обновления_20сегмента_9',['Шаг 1: Инициация обновления сегмента',['../group__public__capital__segment__refresh__process.html#autotoc_md99',1,'']]],
  ['шаг_201_3a_20инициация_20открытия_20проекта_10',['Шаг 1: Инициация открытия проекта',['../group__public__capital__project__opening__process.html#autotoc_md177',1,'']]],
  ['шаг_201_3a_20инициация_20подачи_20голоса_11',['Шаг 1: Инициация подачи голоса',['../group__public__capital__submit__vote__process.html#autotoc_md282',1,'']]],
  ['шаг_201_3a_20инициация_20подсчета_20голосов_12',['Шаг 1: Инициация подсчета голосов',['../group__public__capital__calculate__votes__process.html#autotoc_md271',1,'']]],
  ['шаг_201_3a_20инициация_20удаления_20проекта_13',['Шаг 1: Инициация удаления проекта',['../group__public__capital__project__deletion__process.html#autotoc_md170',1,'']]],
  ['шаг_201_3a_20конвертация_20сегмента_14',['Шаг 1: Конвертация сегмента',['../group__public__capital__conversion__process.html#autotoc_md245',1,'']]],
  ['шаг_201_3a_20назначение_20мастера_20проекта_15',['Шаг 1: Назначение мастера проекта',['../group__public__capital__planning__process.html#autotoc_md197',1,'']]],
  ['шаг_201_3a_20обновление_20кошелька_20программы_16',['Шаг 1: Обновление кошелька программы',['../group__public__capital__refresh__program__process.html#autotoc_md34',1,'']]],
  ['шаг_201_3a_20обновление_20кошелька_20проекта_17',['Шаг 1: Обновление кошелька проекта',['../group__public__capital__refresh__project__process.html#autotoc_md53',1,'']]],
  ['шаг_201_3a_20подача_20договора_20ухд_18',['Шаг 1: Подача договора УХД',['../group__public__capital__registration__process.html#autotoc_md154',1,'']]],
  ['шаг_201_3a_20подача_20заявки_20на_20допуск_20к_20проекту_19',['Шаг 1: Подача заявки на допуск к проекту',['../group__public__capital__joining__process.html#autotoc_md149',1,'']]],
  ['шаг_201_3a_20подача_20заявления_20на_20взнос_20результатом_20',['Шаг 1: Подача заявления на взнос результатом',['../group__public__capital__result__process.html#autotoc_md252',1,'']]],
  ['шаг_201_3a_20регистрация_20членских_20взносов_20программы_21',['Шаг 1: Регистрация членских взносов программы',['../group__public__capital__fundprog__process.html#autotoc_md29',1,'']]],
  ['шаг_201_3a_20регистрация_20членских_20взносов_20проекта_22',['Шаг 1: Регистрация членских взносов проекта',['../group__public__capital__fundproj__process.html#autotoc_md48',1,'']]],
  ['шаг_201_3a_20создание_20заявки_20на_20инвестицию_23',['Шаг 1: Создание заявки на инвестицию',['../group__public__capital__project__investment__process.html#autotoc_md133',1,'']]],
  ['шаг_201_3a_20создание_20заявления_20на_20паевой_20взнос_20имуществом_24',['Шаг 1: Создание заявления на паевой взнос имуществом',['../group__public__capital__project__property__process.html#autotoc_md238',1,'']]],
  ['шаг_201_3a_20создание_20заявления_20на_20получение_20ссуды_25',['Шаг 1: Создание заявления на получение ссуды',['../group__public__capital__debt__process.html#autotoc_md11',1,'']]],
  ['шаг_201_3a_20создание_20заявления_20на_20программный_20имущественный_20взнос_26',['Шаг 1: Создание заявления на программный имущественный взнос',['../group__public__capital__program__property__process.html#autotoc_md227',1,'']]],
  ['шаг_201_3a_20создание_20программной_20инвестиции_27',['Шаг 1: Создание программной инвестиции',['../group__public__capital__program__investment__process.html#autotoc_md125',1,'']]],
  ['шаг_201_3a_20создание_20проекта_28',['Шаг 1: Создание проекта',['../group__public__capital__project__creation__process.html#autotoc_md166',1,'']]],
  ['шаг_202_3a_20валидация_20параметров_20конфигурации_29',['Шаг 2: Валидация параметров конфигурации',['../group__public__capital__configuration__process.html#autotoc_md3',1,'']]],
  ['шаг_202_3a_20добавление_20авторов_20проекта_30',['Шаг 2: Добавление авторов проекта',['../group__public__capital__planning__process.html#autotoc_md198',1,'']]],
  ['шаг_202_3a_20одобрение_20заявки_20председателем_31',['Шаг 2: Одобрение заявки председателем',['../group__public__capital__debt__process.html#autotoc_md12',1,'']]],
  ['шаг_202_3a_20одобрение_20заявления_20председателем_32',['шаг 2: одобрение заявления председателем',['../group__public__capital__program__property__process.html#autotoc_md228',1,'Шаг 2: Одобрение заявления председателем'],['../group__public__capital__result__process.html#autotoc_md253',1,'Шаг 2: Одобрение заявления председателем']]],
  ['шаг_202_3a_20принятие_20имущественного_20взноса_33',['Шаг 2: Принятие имущественного взноса',['../group__public__capital__project__property__process.html#autotoc_md239',1,'']]],
  ['шаг_202_3a_20принятие_20инвестиции_34',['Шаг 2: Принятие инвестиции',['../group__public__capital__project__investment__process.html#autotoc_md134',1,'']]],
  ['шаг_202_3a_20принятие_20приложения_20к_20договору_20ухд_35',['Шаг 2: Принятие приложения к договору УХД',['../group__public__capital__joining__process.html#autotoc_md150',1,'']]],
  ['шаг_202_3a_20принятие_20программной_20инвестиции_36',['Шаг 2: Принятие программной инвестиции',['../group__public__capital__program__investment__process.html#autotoc_md126',1,'']]],
  ['шаг_202_3a_20проверка_20готовности_20проекта_37',['шаг 2: проверка готовности проекта',['../group__public__capital__voting__start__process.html#autotoc_md217',1,'Шаг 2: Проверка готовности проекта'],['../group__public__capital__project__start__process.html#autotoc_md208',1,'Шаг 2: Проверка готовности проекта'],['../group__public__capital__project__opening__process.html#autotoc_md178',1,'Шаг 2: Проверка готовности проекта']]],
  ['шаг_202_3a_20проверка_20статуса_20проекта_38',['шаг 2: проверка статуса проекта',['../group__public__capital__diallocate__process.html#autotoc_md118',1,'Шаг 2: Проверка статуса проекта'],['../group__public__capital__project__deletion__process.html#autotoc_md171',1,'Шаг 2: Проверка статуса проекта']]],
  ['шаг_202_3a_20проверка_20статуса_20проекта_20и_20завершения_20голосования_39',['Шаг 2: Проверка статуса проекта и завершения голосования',['../group__public__capital__calculate__votes__process.html#autotoc_md272',1,'']]],
  ['шаг_202_3a_20проверка_20статуса_20проекта_20и_20срока_20голосования_40',['Шаг 2: Проверка статуса проекта и срока голосования',['../group__public__capital__submit__vote__process.html#autotoc_md283',1,'']]],
  ['шаг_202_3a_20проверка_20существования_20проекта_41',['шаг 2: проверка существования проекта',['../group__public__capital__allocate__process.html#autotoc_md112',1,'Шаг 2: Проверка существования проекта'],['../group__public__capital__segment__refresh__process.html#autotoc_md100',1,'Шаг 2: Проверка существования проекта'],['../group__public__capital__set__master__process.html#autotoc_md186',1,'Шаг 2: Проверка существования проекта']]],
  ['шаг_202_3a_20создание_20записи_20кандидата_20в_20вкладчики_42',['Шаг 2: Создание записи кандидата в вкладчики',['../group__public__capital__registration__process.html#autotoc_md155',1,'']]],
  ['шаг_203_3a_20авторизация_20советом_43',['шаг 3: авторизация советом',['../group__public__capital__program__property__process.html#autotoc_md229',1,'Шаг 3: Авторизация советом'],['../group__public__capital__result__process.html#autotoc_md254',1,'Шаг 3: Авторизация советом'],['../group__public__capital__debt__process.html#autotoc_md13',1,'Шаг 3: Авторизация советом']]],
  ['шаг_203_3a_20валидация_20вкладчика_20голосования_44',['Шаг 3: Валидация вкладчика голосования',['../group__public__capital__submit__vote__process.html#autotoc_md284',1,'']]],
  ['шаг_203_3a_20валидация_20конвертации_20вкладов_45',['Шаг 3: Валидация конвертации вкладов',['../group__public__capital__project__deletion__process.html#autotoc_md172',1,'']]],
  ['шаг_203_3a_20валидация_20суммы_20инвестиций_46',['Шаг 3: Валидация суммы инвестиций',['../group__public__capital__allocate__process.html#autotoc_md113',1,'']]],
  ['шаг_203_3a_20выполнение_20crps_20обновления_47',['Шаг 3: Выполнение CRPS обновления',['../group__public__capital__segment__refresh__process.html#autotoc_md101',1,'']]],
  ['шаг_203_3a_20направление_20на_20одобрение_48',['Шаг 3: Направление на одобрение',['../group__public__capital__registration__process.html#autotoc_md156',1,'']]],
  ['шаг_203_3a_20отклонение_20заявки_20альтернативный_20путь_49',['Шаг 3: Отклонение заявки (альтернативный путь)',['../group__public__capital__joining__process.html#autotoc_md151',1,'']]],
  ['шаг_203_3a_20отклонение_20инвестиции_20альтернативный_20путь_50',['Шаг 3: Отклонение инвестиции (альтернативный путь)',['../group__public__capital__project__investment__process.html#autotoc_md135',1,'']]],
  ['шаг_203_3a_20отклонение_20предложения_20альтернативный_20путь_51',['Шаг 3: Отклонение предложения (альтернативный путь)',['../group__public__capital__project__property__process.html#autotoc_md240',1,'']]],
  ['шаг_203_3a_20отклонение_20программной_20инвестиции_20альтернативный_20путь_52',['Шаг 3: Отклонение программной инвестиции (альтернативный путь)',['../group__public__capital__program__investment__process.html#autotoc_md127',1,'']]],
  ['шаг_203_3a_20открытие_20проекта_53',['Шаг 3: Открытие проекта',['../group__public__capital__project__opening__process.html#autotoc_md179',1,'']]],
  ['шаг_203_3a_20перевод_20в_20активный_20статус_54',['Шаг 3: Перевод в активный статус',['../group__public__capital__project__start__process.html#autotoc_md209',1,'']]],
  ['шаг_203_3a_20перевод_20в_20статус_20голосования_55',['Шаг 3: Перевод в статус голосования',['../group__public__capital__voting__start__process.html#autotoc_md218',1,'']]],
  ['шаг_203_3a_20получение_20сегмента_20вкладчика_56',['Шаг 3: Получение сегмента вкладчика',['../group__public__capital__calculate__votes__process.html#autotoc_md273',1,'']]],
  ['шаг_203_3a_20проверка_20договора_20ухд_20кандидата_57',['Шаг 3: Проверка договора УХД кандидата',['../group__public__capital__set__master__process.html#autotoc_md187',1,'']]],
  ['шаг_203_3a_20проверка_20наличия_20программных_20средств_58',['Шаг 3: Проверка наличия программных средств',['../group__public__capital__diallocate__process.html#autotoc_md119',1,'']]],
  ['шаг_203_3a_20создание_20или_20обновление_20конфигурации_59',['Шаг 3: Создание или обновление конфигурации',['../group__public__capital__configuration__process.html#autotoc_md4',1,'']]],
  ['шаг_203_3a_20установка_20плана_20проекта_60',['Шаг 3: Установка плана проекта',['../group__public__capital__planning__process.html#autotoc_md199',1,'']]],
  ['шаг_204_3a_20авторизация_20регистрации_61',['Шаг 4: Авторизация регистрации',['../group__public__capital__registration__process.html#autotoc_md157',1,'']]],
  ['шаг_204_3a_20аллокация_20средств_20в_20проект_62',['Шаг 4: Аллокация средств в проект',['../group__public__capital__allocate__process.html#autotoc_md114',1,'']]],
  ['шаг_204_3a_20возврат_20неиспользованных_20инвестиций_63',['Шаг 4: Возврат неиспользованных инвестиций',['../group__public__capital__project__investment__process.html#autotoc_md136',1,'']]],
  ['шаг_204_3a_20инициализация_20голосования_20по_20методу_20водянова_64',['Шаг 4: Инициализация голосования по методу Водянова',['../group__public__capital__voting__start__process.html#autotoc_md219',1,'']]],
  ['шаг_204_3a_20подписание_20акта_20№1_20вкладчиком_65',['Шаг 4: Подписание акта №1 вкладчиком',['../group__public__capital__result__process.html#autotoc_md255',1,'']]],
  ['шаг_204_3a_20подписание_20акта_20№1_20участником_66',['Шаг 4: Подписание акта №1 участником',['../group__public__capital__program__property__process.html#autotoc_md230',1,'']]],
  ['шаг_204_3a_20подтверждение_20оплаты_67',['Шаг 4: Подтверждение оплаты',['../group__public__capital__debt__process.html#autotoc_md14',1,'']]],
  ['шаг_204_3a_20проверка_20корректности_20голосов_68',['Шаг 4: Проверка корректности голосов',['../group__public__capital__submit__vote__process.html#autotoc_md285',1,'']]],
  ['шаг_204_3a_20проверка_20участия_20в_20проекте_69',['Шаг 4: Проверка участия в проекте',['../group__public__capital__set__master__process.html#autotoc_md188',1,'']]],
  ['шаг_204_3a_20расчет_20итоговых_20сумм_70',['Шаг 4: Расчет итоговых сумм',['../group__public__capital__calculate__votes__process.html#autotoc_md274',1,'']]],
  ['шаг_204_3a_20расчет_20неиспользованных_20средств_71',['Шаг 4: Расчет неиспользованных средств',['../group__public__capital__diallocate__process.html#autotoc_md120',1,'']]],
  ['шаг_204_3a_20расширение_20расходов_20опционально_72',['Шаг 4: Расширение расходов (опционально)',['../group__public__capital__planning__process.html#autotoc_md200',1,'']]],
  ['шаг_204_3a_20удаление_20связанных_20данных_73',['Шаг 4: Удаление связанных данных',['../group__public__capital__project__deletion__process.html#autotoc_md173',1,'']]],
  ['шаг_205_3a_20активация_20использования_20средств_74',['Шаг 5: Активация использования средств',['../group__public__capital__allocate__process.html#autotoc_md115',1,'']]],
  ['шаг_205_3a_20возврат_20средств_20в_20программу_75',['Шаг 5: Возврат средств в программу',['../group__public__capital__diallocate__process.html#autotoc_md121',1,'']]],
  ['шаг_205_3a_20назначение_20мастера_20проекта_76',['Шаг 5: Назначение мастера проекта',['../group__public__capital__set__master__process.html#autotoc_md189',1,'']]],
  ['шаг_205_3a_20обновление_20сегмента_20вкладчика_77',['Шаг 5: Обновление сегмента вкладчика',['../group__public__capital__calculate__votes__process.html#autotoc_md275',1,'']]],
  ['шаг_205_3a_20погашение_20ссуды_78',['Шаг 5: Погашение ссуды',['../group__public__capital__debt__process.html#autotoc_md18',1,'']]],
  ['шаг_205_3a_20подписание_20акта_20№2_20председателем_79',['Шаг 5: Подписание акта №2 председателем',['../group__public__capital__result__process.html#autotoc_md256',1,'']]],
  ['шаг_205_3a_20подписание_20акта_20№2_20председателем_20и_20зачисление_80',['Шаг 5: Подписание акта №2 председателем и зачисление',['../group__public__capital__program__property__process.html#autotoc_md231',1,'']]],
  ['шаг_205_3a_20сохранение_20голосов_81',['Шаг 5: Сохранение голосов',['../group__public__capital__submit__vote__process.html#autotoc_md286',1,'']]],
  ['шаг_205_3a_20удаление_20записи_20проекта_82',['Шаг 5: Удаление записи проекта',['../group__public__capital__project__deletion__process.html#autotoc_md174',1,'']]],
  ['шаг_206_3a_20завершение_20процесса_83',['Шаг 6: Завершение процесса',['../group__public__capital__diallocate__process.html#autotoc_md122',1,'']]],
  ['шаг_206_3a_20обновление_20счетчика_20полученных_20голосов_84',['Шаг 6: Обновление счетчика полученных голосов',['../group__public__capital__submit__vote__process.html#autotoc_md287',1,'']]]
];
