var searchData=
[
  ['идеократия_20и_20общественно_20полезное_20время_0',['Идеократия и общественно-полезное время',['../group__public__capital.html#autotoc_md296',1,'']]],
  ['из_20программы_1',['из программы',['../group__public__capital__withdraw__from__program__process.html#autotoc_md42',1,'Авторизация возврата из программы'],['../group__public__capital__withdraw__from__program__process.html',1,'Возврат паевого взноса из программы'],['../group__public__capital__withdraw__from__program__process.html#autotoc_md43',1,'Отклонение возврата из программы'],['../group__public__capital__withdraw__from__program__process.html#autotoc_md41',1,'Создание заявления на возврат из программы']]],
  ['из_20проекта_2',['из проекта',['../group__public__capital__withdraw__from__project__process.html#autotoc_md61',1,'Авторизация возврата из проекта'],['../group__public__capital__withdraw__from__project__process.html',1,'Возврат паевого взноса из проекта'],['../group__public__capital__withdraw__from__project__process.html#autotoc_md62',1,'Отклонение возврата из проекта'],['../group__public__capital__withdraw__from__project__process.html#autotoc_md60',1,'Создание заявления на возврат из проекта']]],
  ['иконок_20для_20обозначений_3',['Язык иконок для обозначений',['../group__public__capital.html#autotoc_md294',1,'']]],
  ['или_20обновление_20конфигурации_4',['Шаг 3: Создание или обновление конфигурации',['../group__public__capital__configuration__process.html#autotoc_md4',1,'']]],
  ['имущественного_20взноса_5',['Шаг 2: Принятие имущественного взноса',['../group__public__capital__project__property__process.html#autotoc_md239',1,'']]],
  ['имущественные_20взносы_6',['Имущественные взносы',['../group__public__capital.html#autotoc_md311',1,'']]],
  ['имущественный_20взнос_7',['Шаг 1: Создание заявления на программный имущественный взнос',['../group__public__capital__program__property__process.html#autotoc_md227',1,'']]],
  ['имущественных_20взносов_20в_20программу_8',['Приём имущественных взносов в программу',['../group__public__capital__program__property__process.html',1,'']]],
  ['имущественных_20взносов_20в_20проект_9',['имущественных взносов в проект',['../group__public__capital__project__property__process.html#autotoc_md241',1,'Особенности имущественных взносов в проект'],['../group__public__capital__project__property__process.html',1,'Приём имущественных взносов в проект']]],
  ['имуществом_10',['Шаг 1: Создание заявления на паевой взнос имуществом',['../group__public__capital__project__property__process.html#autotoc_md238',1,'']]],
  ['инвестирование_11',['Прямое инвестирование',['../group__public__capital.html#autotoc_md310',1,'']]],
  ['инвестирования_12',['Открытие инвестирования',['../group__public__capital.html#autotoc_md309',1,'']]],
  ['инвестиции_13',['инвестиции',['../group__public__capital__program__investment__process.html#autotoc_md125',1,'Шаг 1: Создание программной инвестиции'],['../group__public__capital__project__investment__process.html#autotoc_md134',1,'Шаг 2: Принятие инвестиции'],['../group__public__capital__program__investment__process.html#autotoc_md126',1,'Шаг 2: Принятие программной инвестиции']]],
  ['инвестиции_20альтернативный_20путь_14',['инвестиции альтернативный путь',['../group__public__capital__project__investment__process.html#autotoc_md135',1,'Шаг 3: Отклонение инвестиции (альтернативный путь)'],['../group__public__capital__program__investment__process.html#autotoc_md127',1,'Шаг 3: Отклонение программной инвестиции (альтернативный путь)']]],
  ['инвестиции_20в_20программу_15',['Инвестиции в программу',['../group__public__capital__program__investment__process.html',1,'']]],
  ['инвестиции_20в_20проект_16',['Инвестиции в проект',['../group__public__capital__project__investment__process.html',1,'']]],
  ['инвестиций_17',['инвестиций',['../group__public__capital__allocate__process.html',1,'Аллокация программных инвестиций'],['../group__public__capital__unused__return__process.html',1,'Возврат неиспользованных инвестиций'],['../group__public__capital__diallocate__process.html',1,'Деаллокации программных инвестиций'],['../group__public__capital__unused__return__process.html#autotoc_md141',1,'Коэффициент использования инвестиций'],['../group__public__capital__project__opening__process.html',1,'Открытие проекта для инвестиций'],['../group__public__capital.html#autotoc_md308',1,'Фаза 2: Привлечение инвестиций'],['../group__public__capital__allocate__process.html#autotoc_md113',1,'Шаг 3: Валидация суммы инвестиций'],['../group__public__capital__project__investment__process.html#autotoc_md136',1,'Шаг 4: Возврат неиспользованных инвестиций']]],
  ['инвестицию_18',['Шаг 1: Создание заявки на инвестицию',['../group__public__capital__project__investment__process.html#autotoc_md133',1,'']]],
  ['инвестора_19',['Расчёт возврата для инвестора',['../group__public__capital__unused__return__process.html#autotoc_md142',1,'']]],
  ['инициализация_20голосования_20по_20методу_20водянова_20',['Шаг 4: Инициализация голосования по методу Водянова',['../group__public__capital__voting__start__process.html#autotoc_md219',1,'']]],
  ['инициализация_20проекта_21',['Инициализация проекта',['../group__public__capital.html#autotoc_md307',1,'']]],
  ['инициация_20аллокации_20средств_22',['Шаг 1: Инициация аллокации средств',['../group__public__capital__allocate__process.html#autotoc_md111',1,'']]],
  ['инициация_20возврата_20неиспользованных_20средств_23',['Шаг 1: Инициация возврата неиспользованных средств',['../group__public__capital__unused__return__process.html#autotoc_md146',1,'']]],
  ['инициация_20голосования_24',['Шаг 1: Инициация голосования',['../group__public__capital__voting__start__process.html#autotoc_md216',1,'']]],
  ['инициация_20деаллокации_20средств_25',['Шаг 1: Инициация деаллокации средств',['../group__public__capital__diallocate__process.html#autotoc_md117',1,'']]],
  ['инициация_20запуска_20проекта_26',['Шаг 1: Инициация запуска проекта',['../group__public__capital__project__start__process.html#autotoc_md207',1,'']]],
  ['инициация_20назначения_20мастера_27',['Шаг 1: Инициация назначения мастера',['../group__public__capital__set__master__process.html#autotoc_md185',1,'']]],
  ['инициация_20обновления_20сегмента_28',['Шаг 1: Инициация обновления сегмента',['../group__public__capital__segment__refresh__process.html#autotoc_md99',1,'']]],
  ['инициация_20открытия_20проекта_29',['Шаг 1: Инициация открытия проекта',['../group__public__capital__project__opening__process.html#autotoc_md177',1,'']]],
  ['инициация_20подачи_20голоса_30',['Шаг 1: Инициация подачи голоса',['../group__public__capital__submit__vote__process.html#autotoc_md282',1,'']]],
  ['инициация_20подсчета_20голосов_31',['Шаг 1: Инициация подсчета голосов',['../group__public__capital__calculate__votes__process.html#autotoc_md271',1,'']]],
  ['инициация_20удаления_20проекта_32',['Шаг 1: Инициация удаления проекта',['../group__public__capital__project__deletion__process.html#autotoc_md170',1,'']]],
  ['интеграция_20результата_33',['Интеграция результата',['../group__public__capital.html#autotoc_md320',1,'']]],
  ['интеллектуальная_20деятельность_34',['Интеллектуальная деятельность',['../group__public__capital.html#autotoc_md314',1,'']]],
  ['инфраструктурные_20процессы_35',['Инфраструктурные процессы',['../group__public__capital.html#autotoc_md306',1,'']]],
  ['исполнение_20решения_36',['исполнение решения',['../group__public__capital__withdraw__from__program__process.html#autotoc_md40',1,'Исполнение решения'],['../group__public__capital__withdraw__from__project__process.html#autotoc_md59',1,'Исполнение решения']]],
  ['использования_20инвестиций_37',['Коэффициент использования инвестиций',['../group__public__capital__unused__return__process.html#autotoc_md141',1,'']]],
  ['использования_20средств_38',['Шаг 5: Активация использования средств',['../group__public__capital__allocate__process.html#autotoc_md115',1,'']]],
  ['итогового_20вознаграждения_39',['Структура итогового вознаграждения',['../group__public__capital__result__process.html#autotoc_md263',1,'']]],
  ['итоговых_20сумм_40',['Шаг 4: Расчет итоговых сумм',['../group__public__capital__calculate__votes__process.html#autotoc_md274',1,'']]],
  ['и_20авторизация_20расхода_41',['и авторизация расхода',['../group__public__capital__create__expense__process.html#autotoc_md72',1,'Одобрение и авторизация расхода'],['../group__public__capital__create__expense__process.html#autotoc_md75',1,'Одобрение и авторизация расхода']]],
  ['и_20взносов_42',['Расчет затрат и взносов',['../group__public__capital__commit__creation__process.html#autotoc_md92',1,'']]],
  ['и_20завершения_20голосования_43',['Шаг 2: Проверка статуса проекта и завершения голосования',['../group__public__capital__calculate__votes__process.html#autotoc_md272',1,'']]],
  ['и_20зачисление_44',['Шаг 5: Подписание акта №2 председателем и зачисление',['../group__public__capital__program__property__process.html#autotoc_md231',1,'']]],
  ['и_20контроль_45',['Управление и контроль',['../index.html#autotoc_md374',1,'']]],
  ['и_20общественно_20полезное_20время_46',['Идеократия и общественно-полезное время',['../group__public__capital.html#autotoc_md296',1,'']]],
  ['и_20описаний_47',['Список устаревших определений и описаний',['../deprecated.html',1,'']]],
  ['и_20отказы_48',['Альтернативные пути: Отклонение и отказы',['../group__public__capital__debt__process.html#autotoc_md15',1,'']]],
  ['и_20полномочия_20мастера_49',['Роль и полномочия мастера',['../group__public__capital__set__master__process.html#autotoc_md190',1,'']]],
  ['и_20принятие_20решений_50',['Управление и принятие решений',['../index.html#autotoc_md356',1,'']]],
  ['и_20разрешенные_20операции_51',['Состояния проекта и разрешенные операции',['../group__public__capital.html#autotoc_md327',1,'']]],
  ['и_20регистрация_52',['Управление участниками и регистрация',['../index.html#autotoc_md353',1,'']]],
  ['и_20решение_53',['Проблема и решение',['../group__capital__meta__projects.html#autotoc_md331',1,'']]],
  ['и_20срока_20голосования_54',['Шаг 2: Проверка статуса проекта и срока голосования',['../group__public__capital__submit__vote__process.html#autotoc_md283',1,'']]]
];
