var searchData=
[
  ['как_20аккумулятор_0',['Мета-проект как аккумулятор',['../group__capital__meta__projects.html#autotoc_md335',1,'']]],
  ['кандидата_1',['Шаг 3: Проверка договора УХД кандидата',['../group__public__capital__set__master__process.html#autotoc_md187',1,'']]],
  ['кандидата_20в_20вкладчики_2',['Шаг 2: Создание записи кандидата в вкладчики',['../group__public__capital__registration__process.html#autotoc_md155',1,'']]],
  ['капитализации_3',['капитализации',['../group__public__capital.html#autotoc_md303',1,'Комплексная диаграмма всех процессов системы капитализации'],['../group__public__capital.html#autotoc_md300',1,'2. Процесс Капитализации']]],
  ['коммитами_4',['Пример 1: Создатель с коммитами',['../group__public__capital__debt__process.html#autotoc_md20',1,'']]],
  ['коммита_5',['коммита',['../group__public__capital__commit__creation__process.html#autotoc_md91',1,'Проверка уникальности коммита'],['../group__public__capital__commit__creation__process.html#autotoc_md94',1,'Создание коммита'],['../group__public__capital__commit__creation__process.html',1,'Создание коммита']]],
  ['коммита_20в_20ожидании_20одобрения_6',['Создание коммита в ожидании одобрения',['../group__public__capital__commit__creation__process.html#autotoc_md93',1,'']]],
  ['коммита_20мастером_20проекта_7',['коммита мастером проекта',['../group__public__capital__commit__creation__process.html#autotoc_md95',1,'Одобрение коммита мастером проекта'],['../group__public__capital__commit__creation__process.html#autotoc_md96',1,'Отклонение коммита мастером проекта']]],
  ['комплексная_20диаграмма_20всех_20процессов_20системы_20капитализации_8',['Комплексная диаграмма всех процессов системы капитализации',['../group__public__capital.html#autotoc_md303',1,'']]],
  ['комплексное_20описание_20всех_20процессов_20системы_9',['Комплексное описание всех процессов системы',['../group__public__capital.html#autotoc_md304',1,'']]],
  ['компонентов_10',['компонентов',['../group__capital__meta__projects.html#autotoc_md346',1,'Жизненный цикл компонентов'],['../group__capital__meta__projects.html#autotoc_md347',1,'Завершение проектов-компонентов']]],
  ['конвертации_11',['конвертации',['../group__public__capital__conversion__process.html#autotoc_md246',1,'Направления конвертации'],['../group__public__capital__conversion__process.html#autotoc_md249',1,'Ограничения конвертации']]],
  ['конвертации_20вкладов_12',['конвертации вкладов',['../group__public__capital.html#autotoc_md326',1,'Варианты конвертации вкладов'],['../group__public__capital__project__deletion__process.html#autotoc_md172',1,'Шаг 3: Валидация конвертации вкладов']]],
  ['конвертацию_20сегмента_13',['Влияние на конвертацию сегмента',['../group__public__capital__debt__process.html#autotoc_md23',1,'']]],
  ['конвертация_20взноса_20результатом_14',['Конвертация взноса результатом',['../group__public__capital__conversion__process.html',1,'']]],
  ['конвертация_20вкладов_15',['Конвертация вкладов',['../group__capital__meta__projects.html#autotoc_md339',1,'']]],
  ['конвертация_20сегмента_16',['Шаг 1: Конвертация сегмента',['../group__public__capital__conversion__process.html#autotoc_md245',1,'']]],
  ['константы_17',['константы',['../group__public__fund__consts.html',1,'Константы'],['../group__public__wrap__consts.html',1,'Константы'],['../group__public__capital__consts.html',1,'Константы'],['../group__public__token__consts.html',1,'Константы'],['../group__public__system__consts.html',1,'Константы'],['../group__public__draft__consts.html',1,'Константы'],['../group__public__msig__consts.html',1,'Константы'],['../group__public__soviet__consts.html',1,'Константы'],['../group__public__registrator__consts.html',1,'Константы'],['../group__public__meet__consts.html',1,'Константы'],['../group__public__loan__consts.html',1,'Константы'],['../group__public__ledger__consts.html',1,'Константы'],['../group__public__gateway__consts.html',1,'Константы']]],
  ['контракта_18',['Обзор контракта',['../group__public__capital.html',1,'']]],
  ['контракта_20для_20кооператива_19',['Конфигурация контракта для кооператива',['../group__public__capital__configuration__process.html',1,'']]],
  ['контракты_20',['контракты',['../index.html#autotoc_md352',1,'Основные контракты'],['../index.html#autotoc_md370',1,'Системные контракты']]],
  ['контракт_20branch_21',['контракт branch',['../index.html#autotoc_md355',1,'Контракт BRANCH'],['../group__public__branch.html',1,'Контракт BRANCH']]],
  ['контракт_20capital_22',['контракт capital',['../group__public__capital.html',1,'Контракт CAPITAL'],['../index.html#autotoc_md360',1,'Контракт CAPITAL']]],
  ['контракт_20draft_23',['контракт draft',['../group__public__draft.html',1,'Контракт DRAFT'],['../index.html#autotoc_md369',1,'Контракт DRAFT']]],
  ['контракт_20fund_24',['контракт fund',['../group__public__fund.html',1,'Контракт FUND'],['../index.html#autotoc_md361',1,'Контракт FUND']]],
  ['контракт_20gateway_25',['контракт gateway',['../index.html#autotoc_md367',1,'Контракт GATEWAY'],['../group__public__gateway.html',1,'Контракт GATEWAY']]],
  ['контракт_20ledger_26',['контракт ledger',['../index.html#autotoc_md363',1,'Контракт LEDGER'],['../group__public__ledger.html',1,'Контракт LEDGER']]],
  ['контракт_20loan_27',['контракт loan',['../group__public__loan.html',1,'Контракт LOAN'],['../index.html#autotoc_md364',1,'Контракт LOAN']]],
  ['контракт_20marketplace_28',['Контракт MARKETPLACE',['../index.html#autotoc_md366',1,'']]],
  ['контракт_20meet_29',['контракт meet',['../group__public__meet.html',1,'Контракт MEET'],['../index.html#autotoc_md358',1,'Контракт MEET']]],
  ['контракт_20msig_30',['Контракт MSIG',['../group__public__msig.html',1,'']]],
  ['контракт_20registrator_31',['контракт registrator',['../index.html#autotoc_md354',1,'Контракт REGISTRATOR'],['../group__public__registrator.html',1,'Контракт REGISTRATOR']]],
  ['контракт_20soviet_32',['контракт soviet',['../index.html#autotoc_md357',1,'Контракт SOVIET'],['../group__public__soviet.html',1,'Контракт SOVIET']]],
  ['контракт_20system_33',['Контракт SYSTEM',['../group__public__system.html',1,'']]],
  ['контракт_20token_34',['Контракт TOKEN',['../group__public__token.html',1,'']]],
  ['контракт_20wallet_35',['Контракт WALLET',['../index.html#autotoc_md362',1,'']]],
  ['контракт_20wrap_36',['Контракт WRAP',['../group__public__wrap.html',1,'']]],
  ['контроль_37',['Управление и контроль',['../index.html#autotoc_md374',1,'']]],
  ['контроль_20прогресса_38',['Контроль прогресса',['../group__public__capital__project__start__process.html#autotoc_md212',1,'']]],
  ['конфигурации_39',['конфигурации',['../group__public__capital__configuration__process.html#autotoc_md3',1,'Шаг 2: Валидация параметров конфигурации'],['../group__public__capital__configuration__process.html#autotoc_md4',1,'Шаг 3: Создание или обновление конфигурации']]],
  ['конфигурация_20контракта_20для_20кооператива_40',['Конфигурация контракта для кооператива',['../group__public__capital__configuration__process.html',1,'']]],
  ['кооператива_41',['кооператива',['../group__public__capital__configuration__process.html',1,'Конфигурация контракта для кооператива'],['../group__public__capital__configuration__process.html#autotoc_md2',1,'Шаг 1: Авторизация кооператива']]],
  ['координаторам_42',['Пример расчёта (500 часов, 2000 RUB/час, 4% координаторам)',['../group__public__capital__planning__process.html#autotoc_md203',1,'']]],
  ['координатор_43',['Пример 3: Координатор',['../group__public__capital__debt__process.html#autotoc_md22',1,'']]],
  ['корректности_20голосов_44',['Шаг 4: Проверка корректности голосов',['../group__public__capital__submit__vote__process.html#autotoc_md285',1,'']]],
  ['кошелька_20программы_45',['кошелька программы',['../group__public__capital__refresh__program__process.html',1,'Обновление кошелька программы'],['../group__public__capital__refresh__program__process.html#autotoc_md34',1,'Шаг 1: Обновление кошелька программы']]],
  ['кошелька_20проекта_46',['кошелька проекта',['../group__public__capital__refresh__project__process.html',1,'Обновления кошелька проекта'],['../group__public__capital__refresh__project__process.html#autotoc_md53',1,'Шаг 1: Обновление кошелька проекта']]],
  ['коэффициент_20использования_20инвестиций_47',['Коэффициент использования инвестиций',['../group__public__capital__unused__return__process.html#autotoc_md141',1,'']]],
  ['критерии_20завершения_20активной_20фазы_48',['Критерии завершения активной фазы',['../group__public__capital__project__start__process.html#autotoc_md213',1,'']]],
  ['к_20договору_20ухд_49',['Шаг 2: Принятие приложения к договору УХД',['../group__public__capital__joining__process.html#autotoc_md150',1,'']]],
  ['к_20мастеру_50',['Требования к мастеру',['../group__public__capital__set__master__process.html#autotoc_md191',1,'']]],
  ['к_20проекту_51',['к проекту',['../group__public__capital__joining__process.html',1,'Допуск к проекту'],['../group__public__capital__joining__process.html#autotoc_md149',1,'Шаг 1: Подача заявки на допуск к проекту']]]
];
