var searchData=
[
  ['завершение_0',['Фаза 6: Финальное завершение',['../group__public__capital.html#autotoc_md324',1,'']]],
  ['завершение_20голосования_1',['Шаг 1: Завершение голосования',['../group__public__capital__voting__completion__process.html#autotoc_md163',1,'']]],
  ['завершение_20проектов_20компонентов_2',['Завершение проектов-компонентов',['../group__capital__meta__projects.html#autotoc_md347',1,'']]],
  ['завершение_20процесса_3',['Шаг 6: Завершение процесса',['../group__public__capital__diallocate__process.html#autotoc_md122',1,'']]],
  ['завершения_20активной_20фазы_4',['Критерии завершения активной фазы',['../group__public__capital__project__start__process.html#autotoc_md213',1,'']]],
  ['завершения_20голосования_5',['Шаг 2: Проверка статуса проекта и завершения голосования',['../group__public__capital__calculate__votes__process.html#autotoc_md272',1,'']]],
  ['завершить_20голосование_6',['Завершить голосование',['../group__public__capital__voting__completion__process.html',1,'']]],
  ['закрытие_20проекта_7',['Закрытие проекта',['../group__public__capital.html#autotoc_md325',1,'']]],
  ['записи_20кандидата_20в_20вкладчики_8',['Шаг 2: Создание записи кандидата в вкладчики',['../group__public__capital__registration__process.html#autotoc_md155',1,'']]],
  ['записи_20проекта_9',['Шаг 5: Удаление записи проекта',['../group__public__capital__project__deletion__process.html#autotoc_md174',1,'']]],
  ['записи_20расхода_10',['Создание записи расхода',['../group__public__capital__create__expense__process.html#autotoc_md71',1,'']]],
  ['запрос_20регистрации_20доли_20вкладчиком_11',['Запрос регистрации доли вкладчиком',['../group__public__capital__share__registration__process.html#autotoc_md104',1,'']]],
  ['запуска_12',['Операции, доступные после запуска',['../group__public__capital__project__start__process.html#autotoc_md211',1,'']]],
  ['запуска_20генерации_20проекта_13',['Запуска генерации проекта',['../group__public__capital__project__start__process.html',1,'']]],
  ['запуска_20проекта_14',['запуска проекта',['../group__public__capital__project__start__process.html#autotoc_md210',1,'Особенности запуска проекта'],['../group__public__capital__project__start__process.html#autotoc_md207',1,'Шаг 1: Инициация запуска проекта']]],
  ['запуск_20генерации_15',['Запуск генерации',['../group__public__capital.html#autotoc_md313',1,'']]],
  ['затрат_20и_20взносов_16',['Расчет затрат и взносов',['../group__public__capital__commit__creation__process.html#autotoc_md92',1,'']]],
  ['зачисление_17',['Шаг 5: Подписание акта №2 председателем и зачисление',['../group__public__capital__program__property__process.html#autotoc_md231',1,'']]],
  ['заявки_18',['Отклонение заявки',['../group__public__capital__debt__process.html#autotoc_md17',1,'']]],
  ['заявки_20альтернативный_20путь_19',['Шаг 3: Отклонение заявки (альтернативный путь)',['../group__public__capital__joining__process.html#autotoc_md151',1,'']]],
  ['заявки_20на_20допуск_20к_20проекту_20',['Шаг 1: Подача заявки на допуск к проекту',['../group__public__capital__joining__process.html#autotoc_md149',1,'']]],
  ['заявки_20на_20инвестицию_21',['Шаг 1: Создание заявки на инвестицию',['../group__public__capital__project__investment__process.html#autotoc_md133',1,'']]],
  ['заявки_20председателем_22',['Шаг 2: Одобрение заявки председателем',['../group__public__capital__debt__process.html#autotoc_md12',1,'']]],
  ['заявления_23',['Альтернативные пути: Отклонение заявления',['../group__public__capital__result__process.html#autotoc_md257',1,'']]],
  ['заявления_20вкладчиком_24',['заявления вкладчиком',['../group__public__capital__withdraw__from__project__process.html#autotoc_md56',1,'Подача заявления вкладчиком'],['../group__public__capital__withdraw__from__program__process.html#autotoc_md37',1,'Подача заявления вкладчиком']]],
  ['заявления_20на_20взнос_20результатом_25',['Шаг 1: Подача заявления на взнос результатом',['../group__public__capital__result__process.html#autotoc_md252',1,'']]],
  ['заявления_20на_20возврат_20из_20программы_26',['Создание заявления на возврат из программы',['../group__public__capital__withdraw__from__program__process.html#autotoc_md41',1,'']]],
  ['заявления_20на_20возврат_20из_20проекта_27',['Создание заявления на возврат из проекта',['../group__public__capital__withdraw__from__project__process.html#autotoc_md60',1,'']]],
  ['заявления_20на_20паевой_20взнос_20имуществом_28',['Шаг 1: Создание заявления на паевой взнос имуществом',['../group__public__capital__project__property__process.html#autotoc_md238',1,'']]],
  ['заявления_20на_20получение_20ссуды_29',['Шаг 1: Создание заявления на получение ссуды',['../group__public__capital__debt__process.html#autotoc_md11',1,'']]],
  ['заявления_20на_20программный_20имущественный_20взнос_30',['Шаг 1: Создание заявления на программный имущественный взнос',['../group__public__capital__program__property__process.html#autotoc_md227',1,'']]],
  ['заявления_20о_20расходе_31',['заявления о расходе',['../group__public__capital__create__expense__process.html#autotoc_md66',1,'Подача заявления о расходе'],['../group__public__capital__create__expense__process.html#autotoc_md74',1,'Создание заявления о расходе']]],
  ['заявления_20председателем_32',['заявления председателем',['../group__public__capital__result__process.html#autotoc_md253',1,'Шаг 2: Одобрение заявления председателем'],['../group__public__capital__program__property__process.html#autotoc_md228',1,'Шаг 2: Одобрение заявления председателем']]]
];
