var searchData=
[
  ['валидация_20вкладчика_20голосования_0',['Шаг 3: Валидация вкладчика голосования',['../group__public__capital__submit__vote__process.html#autotoc_md284',1,'']]],
  ['валидация_20дополнительных_20расходов_1',['Валидация дополнительных расходов',['../group__public__capital__expand__expenses__process.html#autotoc_md84',1,'']]],
  ['валидация_20конвертации_20вкладов_2',['Шаг 3: Валидация конвертации вкладов',['../group__public__capital__project__deletion__process.html#autotoc_md172',1,'']]],
  ['валидация_20параметров_20конфигурации_3',['Шаг 2: Валидация параметров конфигурации',['../group__public__capital__configuration__process.html#autotoc_md3',1,'']]],
  ['валидация_20прав_20создателя_4',['Валидация прав создателя',['../group__public__capital__commit__creation__process.html#autotoc_md90',1,'']]],
  ['валидация_20суммы_20инвестиций_5',['Шаг 3: Валидация суммы инвестиций',['../group__public__capital__allocate__process.html#autotoc_md113',1,'']]],
  ['варианты_20конвертации_20вкладов_6',['Варианты конвертации вкладов',['../group__public__capital.html#autotoc_md326',1,'']]],
  ['вероятно_7',['вероятно',['../project-property-docs_8dox.html#ae66528efb82a2b3050eadba453d15896',1,'project-property-docs.dox']]],
  ['взноса_8',['взноса',['../group__public__capital__program__property__process.html#autotoc_md232',1,'Альтернативный путь: Отклонение взноса'],['../group__public__capital__result__process.html#autotoc_md261',1,'Природа паевого взноса'],['../group__public__capital__project__property__process.html#autotoc_md239',1,'Шаг 2: Принятие имущественного взноса']]],
  ['взноса_20из_20программы_9',['Возврат паевого взноса из программы',['../group__public__capital__withdraw__from__program__process.html',1,'']]],
  ['взноса_20из_20проекта_10',['Возврат паевого взноса из проекта',['../group__public__capital__withdraw__from__project__process.html',1,'']]],
  ['взноса_20результатом_11',['взноса результатом',['../group__public__capital__conversion__process.html',1,'Конвертация взноса результатом'],['../group__public__capital__result__process.html#autotoc_md260',1,'Правовые аспекты взноса результатом']]],
  ['взносов_12',['Расчет затрат и взносов',['../group__public__capital__commit__creation__process.html#autotoc_md92',1,'']]],
  ['взносов_20в_20программу_13',['Приём имущественных взносов в программу',['../group__public__capital__program__property__process.html',1,'']]],
  ['взносов_20в_20проект_14',['взносов в проект',['../group__public__capital__project__property__process.html#autotoc_md241',1,'Особенности имущественных взносов в проект'],['../group__public__capital__project__property__process.html',1,'Приём имущественных взносов в проект']]],
  ['взносов_20на_20программу_15',['Фондирование членских взносов на программу',['../group__public__capital__fundprog__process.html',1,'']]],
  ['взносов_20на_20проект_16',['Фондирование членских взносов на проект',['../group__public__capital__fundproj__process.html',1,'']]],
  ['взносов_20программы_17',['Шаг 1: Регистрация членских взносов программы',['../group__public__capital__fundprog__process.html#autotoc_md29',1,'']]],
  ['взносов_20проекта_18',['Шаг 1: Регистрация членских взносов проекта',['../group__public__capital__fundproj__process.html#autotoc_md48',1,'']]],
  ['взносы_19',['Имущественные взносы',['../group__public__capital.html#autotoc_md311',1,'']]],
  ['взнос_20',['Шаг 1: Создание заявления на программный имущественный взнос',['../group__public__capital__program__property__process.html#autotoc_md227',1,'']]],
  ['взнос_20имуществом_21',['Шаг 1: Создание заявления на паевой взнос имуществом',['../group__public__capital__project__property__process.html#autotoc_md238',1,'']]],
  ['взнос_20результатом_22',['Шаг 1: Подача заявления на взнос результатом',['../group__public__capital__result__process.html#autotoc_md252',1,'']]],
  ['вкладов_23',['вкладов',['../group__public__capital.html#autotoc_md326',1,'Варианты конвертации вкладов'],['../group__capital__meta__projects.html#autotoc_md339',1,'Конвертация вкладов'],['../group__public__capital.html#autotoc_md321',1,'Финализация вкладов'],['../group__public__capital__project__deletion__process.html#autotoc_md172',1,'Шаг 3: Валидация конвертации вкладов']]],
  ['вкладчика_24',['вкладчика',['../group__public__capital__share__registration__process.html#autotoc_md108',1,'Регистрация доли вкладчика'],['../group__public__capital__share__registration__process.html#autotoc_md107',1,'Регистрация доли вкладчика'],['../group__public__capital__share__registration__process.html',1,'Регистрация доли вкладчика'],['../group__public__capital__calculate__votes__process.html#autotoc_md273',1,'Шаг 3: Получение сегмента вкладчика'],['../group__public__capital__calculate__votes__process.html#autotoc_md275',1,'Шаг 5: Обновление сегмента вкладчика']]],
  ['вкладчика_20голосования_25',['Шаг 3: Валидация вкладчика голосования',['../group__public__capital__submit__vote__process.html#autotoc_md284',1,'']]],
  ['вкладчики_26',['Шаг 2: Создание записи кандидата в вкладчики',['../group__public__capital__registration__process.html#autotoc_md155',1,'']]],
  ['вкладчиков_27',['вкладчиков',['../group__capital__meta__projects.html#autotoc_md344',1,'Поэтапное накопление вкладчиков'],['../group__capital__meta__projects.html#autotoc_md336',1,'Принцип накопления вкладчиков'],['../group__public__capital__registration__process.html',1,'Регистрация вкладчиков']]],
  ['вкладчиком_28',['вкладчиком',['../group__public__capital__share__registration__process.html#autotoc_md104',1,'Запрос регистрации доли вкладчиком'],['../group__public__capital__withdraw__from__project__process.html#autotoc_md56',1,'Подача заявления вкладчиком'],['../group__public__capital__withdraw__from__program__process.html#autotoc_md37',1,'Подача заявления вкладчиком'],['../group__public__capital__result__process.html#autotoc_md255',1,'Шаг 4: Подписание акта №1 вкладчиком']]],
  ['влияние_20на_20жизненный_20цикл_20проекта_29',['Влияние на жизненный цикл проекта',['../group__public__capital__set__master__process.html#autotoc_md193',1,'']]],
  ['влияние_20на_20конвертацию_20сегмента_30',['Влияние на конвертацию сегмента',['../group__public__capital__debt__process.html#autotoc_md23',1,'']]],
  ['внесение_20результата_31',['Внесение результата',['../group__public__capital__result__process.html',1,'']]],
  ['водянова_32',['водянова',['../group__public__capital.html#autotoc_md318',1,'Голосование по методу Водянова'],['../group__public__capital__submit__vote__process.html',1,'Голосование по методу Водянова'],['../group__public__capital__calculate__votes__process.html',1,'Подсчет голосов по методу Водянова'],['../group__public__capital__voting__start__process.html#autotoc_md220',1,'Расчет сумм по методу Водянова'],['../group__public__capital__voting__start__process.html#autotoc_md219',1,'Шаг 4: Инициализация голосования по методу Водянова']]],
  ['водянову_33',['Метод расчета по Водянову',['../group__public__capital__calculate__votes__process.html#autotoc_md276',1,'']]],
  ['возврата_34',['Предварительные условия для возврата',['../group__public__capital__unused__return__process.html#autotoc_md145',1,'']]],
  ['возврата_20для_20инвестора_35',['Расчёт возврата для инвестора',['../group__public__capital__unused__return__process.html#autotoc_md142',1,'']]],
  ['возврата_20из_20программы_36',['возврата из программы',['../group__public__capital__withdraw__from__program__process.html#autotoc_md42',1,'Авторизация возврата из программы'],['../group__public__capital__withdraw__from__program__process.html#autotoc_md43',1,'Отклонение возврата из программы']]],
  ['возврата_20из_20проекта_37',['возврата из проекта',['../group__public__capital__withdraw__from__project__process.html#autotoc_md61',1,'Авторизация возврата из проекта'],['../group__public__capital__withdraw__from__project__process.html#autotoc_md62',1,'Отклонение возврата из проекта']]],
  ['возврата_20неиспользованных_20средств_38',['Шаг 1: Инициация возврата неиспользованных средств',['../group__public__capital__unused__return__process.html#autotoc_md146',1,'']]],
  ['возврат_20из_20программы_39',['Создание заявления на возврат из программы',['../group__public__capital__withdraw__from__program__process.html#autotoc_md41',1,'']]],
  ['возврат_20из_20проекта_40',['Создание заявления на возврат из проекта',['../group__public__capital__withdraw__from__project__process.html#autotoc_md60',1,'']]],
  ['возврат_20неиспользованных_20инвестиций_41',['возврат неиспользованных инвестиций',['../group__public__capital__unused__return__process.html',1,'Возврат неиспользованных инвестиций'],['../group__public__capital__project__investment__process.html#autotoc_md136',1,'Шаг 4: Возврат неиспользованных инвестиций']]],
  ['возврат_20паевого_20взноса_20из_20программы_42',['Возврат паевого взноса из программы',['../group__public__capital__withdraw__from__program__process.html',1,'']]],
  ['возврат_20паевого_20взноса_20из_20проекта_43',['Возврат паевого взноса из проекта',['../group__public__capital__withdraw__from__project__process.html',1,'']]],
  ['возврат_20средств_20в_20программу_44',['Шаг 5: Возврат средств в программу',['../group__public__capital__diallocate__process.html#autotoc_md121',1,'']]],
  ['вознаграждения_45',['Структура итогового вознаграждения',['../group__public__capital__result__process.html#autotoc_md263',1,'']]],
  ['время_46',['Идеократия и общественно-полезное время',['../group__public__capital.html#autotoc_md296',1,'']]],
  ['всех_20процессов_20системы_47',['Комплексное описание всех процессов системы',['../group__public__capital.html#autotoc_md304',1,'']]],
  ['всех_20процессов_20системы_20капитализации_48',['Комплексная диаграмма всех процессов системы капитализации',['../group__public__capital.html#autotoc_md303',1,'']]],
  ['вспомогательные_20системы_49',['Вспомогательные системы',['../index.html#autotoc_md368',1,'']]],
  ['второе_50',['второе',['../project-property-docs_8dox.html#ab973547a4cb5893dcfe8575cf782ceab',1,'project-property-docs.dox']]],
  ['выгоды_51',['Механизм централизованной выгоды',['../group__capital__meta__projects.html#autotoc_md338',1,'']]],
  ['выдача_20ссуды_52',['Выдача ссуды',['../group__public__capital__debt__process.html',1,'']]],
  ['выдачу_53',['Ограничения на выдачу',['../group__public__capital__debt__process.html#autotoc_md8',1,'']]],
  ['выполнение_20расширения_20плана_20расходов_54',['Выполнение расширения плана расходов',['../group__public__capital__expand__expenses__process.html#autotoc_md86',1,'']]],
  ['выполнение_20crps_20обновления_55',['Шаг 3: Выполнение CRPS обновления',['../group__public__capital__segment__refresh__process.html#autotoc_md101',1,'']]],
  ['выполнения_20платежа_56',['Подтверждение выполнения платежа',['../group__public__capital__create__expense__process.html#autotoc_md77',1,'']]],
  ['в_20активный_20статус_57',['Шаг 3: Перевод в активный статус',['../group__public__capital__project__start__process.html#autotoc_md209',1,'']]],
  ['в_20вкладчики_58',['Шаг 2: Создание записи кандидата в вкладчики',['../group__public__capital__registration__process.html#autotoc_md155',1,'']]],
  ['в_20магазине_20приложений_59',['Проблема публикации в магазине приложений',['../group__capital__meta__projects.html#autotoc_md332',1,'']]],
  ['в_20ожидании_20одобрения_60',['Создание коммита в ожидании одобрения',['../group__public__capital__commit__creation__process.html#autotoc_md93',1,'']]],
  ['в_20оплате_20gateway_61',['Отказ в оплате Gateway',['../group__public__capital__debt__process.html#autotoc_md16',1,'']]],
  ['в_20программу_62',['в программу',['../group__public__capital__program__investment__process.html',1,'Инвестиции в программу'],['../group__public__capital__program__property__process.html',1,'Приём имущественных взносов в программу'],['../group__public__capital__diallocate__process.html#autotoc_md121',1,'Шаг 5: Возврат средств в программу']]],
  ['в_20проекте_63',['в проекте',['../group__public__capital__create__expense__process.html#autotoc_md67',1,'Проверка участия в проекте'],['../group__public__capital__set__master__process.html#autotoc_md188',1,'Шаг 4: Проверка участия в проекте']]],
  ['в_20проект_64',['в проект',['../group__public__capital__project__investment__process.html',1,'Инвестиции в проект'],['../group__public__capital__project__property__process.html#autotoc_md241',1,'Особенности имущественных взносов в проект'],['../group__public__capital__project__property__process.html',1,'Приём имущественных взносов в проект'],['../group__public__capital__allocate__process.html#autotoc_md114',1,'Шаг 4: Аллокация средств в проект']]],
  ['в_20статус_20голосования_65',['Шаг 3: Перевод в статус голосования',['../group__public__capital__voting__start__process.html#autotoc_md218',1,'']]]
];
