site_name: Кооперативная Экономика

extra_javascript:
  - js/metrika.js

extra_css:
  - css/extra.css
  
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - announce.dismiss   # позволяет закрывать баннер
    - navigation.tracking
    # - navigation.path
    - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.expand
    # - toc.follow
    - toc.integrate
    - search.share
    - navigation.top
    - navigation.footer
    
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal
  
  logo: assets/logo-white.png

  language: ru
  
    
repo_url: https://github.com/coopenomics

plugins:
  - search
  - section-index
  # - group
  # - awesome-pages
  # - table-reader
  # - social:https://squidfunk.github.io/mkdocs-material/
  #   cards_layout: default

  # - literate-nav:
  # nav_file: SUMMARY.md

extra:
  # homepage: 'doctrine'
  generator: false
  # social:
  #   - icon: fontawesome/brands/telegram
  #     link: https://twitter.com/your-profile
  
copyright: АНО «КООПЕРАТИВНАЯ ЭКОНОМИКА» &copy; 2025

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    # - pymdownx.superfences:
    #   custom_fences:
    #     - name: mermaid
    #       class: mermaid
    #       format: !!python/name:pymdownx.superfences.fence_code_format

      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_code_format


  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Манифест: index.md
  # - Идеократия: 
    # - Кратко об Идеократии: documentation/capitalization/short-ideocraty.md
    # - Идеократия Кооперативной Экономики: documentation/capitalization/ideocraty.md
  - Документация: 
    - Введение: documentation/intro.md
    - Обзор: documentation/overview.md
    # - Карта пайщика: documentation/cardcoop.md 
    - Блокчейн:
      - Введение: documentation/blockchain/intro.md
      - Аккаунты, ключи и подписи: documentation/blockchain/accounts.md
      - Действия и транзакции: documentation/blockchain/transactions.md
      - Ноды и синхронизация истории: documentation/blockchain/nodes.md
      - База данных: documentation/blockchain/state.md
      - Компоненты: documentation/blockchain/components.md
      - Протоколы: documentation/blockchain/protocols.md
      - Делегаты и консенсус: documentation/blockchain/witnesses.md 
      - Параметры конфигурации: documentation/blockchain/configuration.md
      
    - Контракты: 
      - Введение: documentation/contracts/index.md
      # - Системные контракты: documentation/coopcontracts/system.md
      # - Кооперативные контракты: documentation/coopcontracts/coopcontracts.md
      # - Контракт "Капитализация": documentation/coopcontracts/capital/index.md
    - Фабрика документов: 
      - Введение: documentation/fabric/intro.md
    - Словарь: vocabulary.md    
      
  
  - Блог: https://blog.coopenomics.world
  - Подключение: providers.md
  # - Инструкции:
  #       - Быстрый старт: documentation/blockchain/install.md
  #       # - Полный старт: documentation/blockchain/install.md
  #       # - Командный кошелёк: https://google.com
  #       # - Синхронизация: documentation/blockchain/sync.md
  #       # - API: https://developers.eos.io/welcome/latest/reference/index
    
  # - Вопрос-ответ: faq.md
  - Контакты: contacts.md
  
  # - Программные Модули: modules.md
      
