var searchData=
[
  ['обзор_0',['Обзор',['../index.html#autotoc_md350',1,'']]],
  ['обзор_20контракта_1',['Обзор контракта',['../group__public__capital.html',1,'']]],
  ['обновление_20конфигурации_2',['Шаг 3: Создание или обновление конфигурации',['../group__public__capital__configuration__process.html#autotoc_md4',1,'']]],
  ['обновление_20кошелька_20программы_3',['обновление кошелька программы',['../group__public__capital__refresh__program__process.html',1,'Обновление кошелька программы'],['../group__public__capital__refresh__program__process.html#autotoc_md34',1,'Шаг 1: Обновление кошелька программы']]],
  ['обновление_20кошелька_20проекта_4',['Шаг 1: Обновление кошелька проекта',['../group__public__capital__refresh__project__process.html#autotoc_md53',1,'']]],
  ['обновление_20сегмента_20вкладчика_5',['Шаг 5: Обновление сегмента вкладчика',['../group__public__capital__calculate__votes__process.html#autotoc_md275',1,'']]],
  ['обновление_20счетчика_20полученных_20голосов_6',['Шаг 6: Обновление счетчика полученных голосов',['../group__public__capital__submit__vote__process.html#autotoc_md287',1,'']]],
  ['обновления_7',['Шаг 3: Выполнение CRPS обновления',['../group__public__capital__segment__refresh__process.html#autotoc_md101',1,'']]],
  ['обновления_20кошелька_20проекта_8',['Обновления кошелька проекта',['../group__public__capital__refresh__project__process.html',1,'']]],
  ['обновления_20сегмента_9',['Шаг 1: Инициация обновления сегмента',['../group__public__capital__segment__refresh__process.html#autotoc_md99',1,'']]],
  ['обновления_20сегмента_20участника_10',['Обновления сегмента участника',['../group__public__capital__segment__refresh__process.html',1,'']]],
  ['обозначений_11',['Язык иконок для обозначений',['../group__public__capital.html#autotoc_md294',1,'']]],
  ['обоснование_12',['Обоснование',['../group__public__capital.html#autotoc_md295',1,'']]],
  ['общественно_20полезное_20время_13',['Идеократия и общественно-полезное время',['../group__public__capital.html#autotoc_md296',1,'']]],
  ['ограничения_14',['Технические ограничения',['../group__capital__meta__projects.html#autotoc_md349',1,'']]],
  ['ограничения_20конвертации_15',['Ограничения конвертации',['../group__public__capital__conversion__process.html#autotoc_md249',1,'']]],
  ['ограничения_20на_20выдачу_16',['Ограничения на выдачу',['../group__public__capital__debt__process.html#autotoc_md8',1,'']]],
  ['одобрение_17',['Шаг 3: Направление на одобрение',['../group__public__capital__registration__process.html#autotoc_md156',1,'']]],
  ['одобрение_20заявки_20председателем_18',['Шаг 2: Одобрение заявки председателем',['../group__public__capital__debt__process.html#autotoc_md12',1,'']]],
  ['одобрение_20заявления_20председателем_19',['одобрение заявления председателем',['../group__public__capital__program__property__process.html#autotoc_md228',1,'Шаг 2: Одобрение заявления председателем'],['../group__public__capital__result__process.html#autotoc_md253',1,'Шаг 2: Одобрение заявления председателем']]],
  ['одобрение_20и_20авторизация_20расхода_20',['одобрение и авторизация расхода',['../group__public__capital__create__expense__process.html#autotoc_md75',1,'Одобрение и авторизация расхода'],['../group__public__capital__create__expense__process.html#autotoc_md72',1,'Одобрение и авторизация расхода']]],
  ['одобрение_20коммита_20мастером_20проекта_21',['Одобрение коммита мастером проекта',['../group__public__capital__commit__creation__process.html#autotoc_md95',1,'']]],
  ['одобрения_22',['Создание коммита в ожидании одобрения',['../group__public__capital__commit__creation__process.html#autotoc_md93',1,'']]],
  ['ожидании_20одобрения_23',['Создание коммита в ожидании одобрения',['../group__public__capital__commit__creation__process.html#autotoc_md93',1,'']]],
  ['операции_24',['операции',['../group__public__capital.html#autotoc_md327',1,'Состояния проекта и разрешенные операции'],['../group__public__capital.html#autotoc_md315',1,'Финансовые операции']]],
  ['операции_20доступные_20после_20запуска_25',['Операции, доступные после запуска',['../group__public__capital__project__start__process.html#autotoc_md211',1,'']]],
  ['описание_26',['описание',['../group__public__capital__program__property__process.html#autotoc_md226',1,'Пошаговое описание'],['../group__public__capital__program__investment__process.html#autotoc_md124',1,'Пошаговое описание'],['../group__public__capital__project__investment__process.html#autotoc_md132',1,'Пошаговое описание'],['../group__public__capital__unused__return__process.html#autotoc_md144',1,'Пошаговое описание'],['../group__public__capital__project__property__process.html#autotoc_md237',1,'Пошаговое описание'],['../group__public__capital__result__process.html#autotoc_md251',1,'Пошаговое описание'],['../group__public__capital__refresh__project__process.html#autotoc_md52',1,'Пошаговое описание'],['../group__public__capital__fundproj__process.html#autotoc_md47',1,'Пошаговое описание'],['../group__public__capital__refresh__program__process.html#autotoc_md33',1,'Пошаговое описание'],['../group__public__capital__fundprog__process.html#autotoc_md28',1,'Пошаговое описание'],['../group__public__capital__debt__process.html#autotoc_md10',1,'Пошаговое описание']]],
  ['описание_20всех_20процессов_20системы_27',['Комплексное описание всех процессов системы',['../group__public__capital.html#autotoc_md304',1,'']]],
  ['описание_20процесса_28',['описание процесса',['../group__public__capital__project__creation__process.html#autotoc_md165',1,'Пошаговое описание процесса'],['../group__public__capital__conversion__process.html#autotoc_md244',1,'Пошаговое описание процесса'],['../group__public__capital__registration__process.html#autotoc_md153',1,'Пошаговое описание процесса'],['../group__public__capital__project__deletion__process.html#autotoc_md169',1,'Пошаговое описание процесса'],['../group__public__capital__project__opening__process.html#autotoc_md176',1,'Пошаговое описание процесса'],['../group__public__capital__set__master__process.html#autotoc_md184',1,'Пошаговое описание процесса'],['../group__public__capital__submit__vote__process.html#autotoc_md281',1,'Пошаговое описание процесса'],['../group__public__capital__planning__process.html#autotoc_md196',1,'Пошаговое описание процесса'],['../group__public__capital__calculate__votes__process.html#autotoc_md270',1,'Пошаговое описание процесса'],['../group__public__capital__project__start__process.html#autotoc_md206',1,'Пошаговое описание процесса'],['../group__public__capital__voting__start__process.html#autotoc_md215',1,'Пошаговое описание процесса'],['../group__public__capital__voting__completion__process.html#autotoc_md162',1,'Пошаговое описание процесса'],['../group__public__capital__segment__refresh__process.html#autotoc_md98',1,'Пошаговое описание процесса'],['../group__public__capital__allocate__process.html#autotoc_md110',1,'Пошаговое описание процесса'],['../group__public__capital__diallocate__process.html#autotoc_md116',1,'Пошаговое описание процесса'],['../group__public__capital__configuration__process.html#autotoc_md1',1,'Пошаговое описание процесса']]],
  ['описаний_29',['Список устаревших определений и описаний',['../deprecated.html',1,'']]],
  ['оплате_20gateway_30',['Отказ в оплате Gateway',['../group__public__capital__debt__process.html#autotoc_md16',1,'']]],
  ['оплаты_31',['Шаг 4: Подтверждение оплаты',['../group__public__capital__debt__process.html#autotoc_md14',1,'']]],
  ['оплаты_20расхода_32',['Подтверждение оплаты расхода',['../group__public__capital__create__expense__process.html#autotoc_md73',1,'']]],
  ['определений_20и_20описаний_33',['Список устаревших определений и описаний',['../deprecated.html',1,'']]],
  ['опционально_34',['Шаг 4: Расширение расходов (опционально)',['../group__public__capital__planning__process.html#autotoc_md200',1,'']]],
  ['основной_20процесс_20жизненного_20цикла_20проекта_35',['Основной процесс жизненного цикла проекта',['../group__public__capital.html#autotoc_md301',1,'']]],
  ['основные_20контракты_36',['Основные контракты',['../index.html#autotoc_md352',1,'']]],
  ['основные_20принципы_37',['Основные принципы',['../group__capital__meta__projects.html#autotoc_md334',1,'']]],
  ['основные_20термины_38',['Основные термины',['../group__public__capital.html#autotoc_md293',1,'']]],
  ['основных_20процесса_20модели_39',['Два основных процесса модели',['../group__public__capital.html#autotoc_md297',1,'']]],
  ['основы_20планирования_40',['Математические основы планирования',['../group__public__capital__planning__process.html#autotoc_md201',1,'']]],
  ['основы_20расчёта_41',['Математические основы расчёта',['../group__public__capital__unused__return__process.html#autotoc_md140',1,'']]],
  ['основы_20расчёта_20ссуд_42',['Математические основы расчёта ссуд',['../group__public__capital__debt__process.html#autotoc_md6',1,'']]],
  ['особенности_20запуска_20проекта_43',['Особенности запуска проекта',['../group__public__capital__project__start__process.html#autotoc_md210',1,'']]],
  ['особенности_20имущественных_20взносов_20в_20проект_44',['Особенности имущественных взносов в проект',['../group__public__capital__project__property__process.html#autotoc_md241',1,'']]],
  ['остаточными_20средствами_45',['Управление остаточными средствами',['../group__public__capital.html#autotoc_md322',1,'']]],
  ['отказы_46',['Альтернативные пути: Отклонение и отказы',['../group__public__capital__debt__process.html#autotoc_md15',1,'']]],
  ['отказ_20в_20оплате_20gateway_47',['Отказ в оплате Gateway',['../group__public__capital__debt__process.html#autotoc_md16',1,'']]],
  ['отклонение_20взноса_48',['Альтернативный путь: Отклонение взноса',['../group__public__capital__program__property__process.html#autotoc_md232',1,'']]],
  ['отклонение_20возврата_20из_20программы_49',['Отклонение возврата из программы',['../group__public__capital__withdraw__from__program__process.html#autotoc_md43',1,'']]],
  ['отклонение_20возврата_20из_20проекта_50',['Отклонение возврата из проекта',['../group__public__capital__withdraw__from__project__process.html#autotoc_md62',1,'']]],
  ['отклонение_20заявки_51',['Отклонение заявки',['../group__public__capital__debt__process.html#autotoc_md17',1,'']]],
  ['отклонение_20заявки_20альтернативный_20путь_52',['Шаг 3: Отклонение заявки (альтернативный путь)',['../group__public__capital__joining__process.html#autotoc_md151',1,'']]],
  ['отклонение_20заявления_53',['Альтернативные пути: Отклонение заявления',['../group__public__capital__result__process.html#autotoc_md257',1,'']]],
  ['отклонение_20инвестиции_20альтернативный_20путь_54',['Шаг 3: Отклонение инвестиции (альтернативный путь)',['../group__public__capital__project__investment__process.html#autotoc_md135',1,'']]],
  ['отклонение_20и_20отказы_55',['Альтернативные пути: Отклонение и отказы',['../group__public__capital__debt__process.html#autotoc_md15',1,'']]],
  ['отклонение_20коммита_20мастером_20проекта_56',['Отклонение коммита мастером проекта',['../group__public__capital__commit__creation__process.html#autotoc_md96',1,'']]],
  ['отклонение_20предложения_20альтернативный_20путь_57',['Шаг 3: Отклонение предложения (альтернативный путь)',['../group__public__capital__project__property__process.html#autotoc_md240',1,'']]],
  ['отклонение_20председателем_58',['Отклонение председателем',['../group__public__capital__result__process.html#autotoc_md258',1,'']]],
  ['отклонение_20программной_20инвестиции_20альтернативный_20путь_59',['Шаг 3: Отклонение программной инвестиции (альтернативный путь)',['../group__public__capital__program__investment__process.html#autotoc_md127',1,'']]],
  ['отклонение_20расхода_60',['Отклонение расхода',['../group__public__capital__create__expense__process.html#autotoc_md76',1,'']]],
  ['отклонение_20советом_61',['Отклонение советом',['../group__public__capital__result__process.html#autotoc_md259',1,'']]],
  ['открытие_20инвестирования_62',['Открытие инвестирования',['../group__public__capital.html#autotoc_md309',1,'']]],
  ['открытие_20проекта_63',['Шаг 3: Открытие проекта',['../group__public__capital__project__opening__process.html#autotoc_md179',1,'']]],
  ['открытие_20проекта_20для_20инвестиций_64',['Открытие проекта для инвестиций',['../group__public__capital__project__opening__process.html',1,'']]],
  ['открытия_65',['Условия для открытия',['../group__public__capital__project__opening__process.html#autotoc_md180',1,'']]],
  ['открытия_20проекта_66',['Шаг 1: Инициация открытия проекта',['../group__public__capital__project__opening__process.html#autotoc_md177',1,'']]],
  ['открыть_20голосование_67',['Открыть голосование',['../group__public__capital__voting__start__process.html',1,'']]],
  ['оценка_20результата_68',['Фаза 4: Оценка результата',['../group__public__capital.html#autotoc_md317',1,'']]],
  ['о_20расходе_69',['о расходе',['../group__public__capital__create__expense__process.html#autotoc_md66',1,'Подача заявления о расходе'],['../group__public__capital__create__expense__process.html#autotoc_md74',1,'Создание заявления о расходе']]]
];
