var dir_99d6a2ec44a7d22665ead9c94e1d5c22 =
[
    [ "account_payer.hpp", "account__payer_8hpp.html", "account__payer_8hpp" ],
    [ "coops_access_helpers.hpp", "coops__access__helpers_8hpp.html", "coops__access__helpers_8hpp" ],
    [ "document_core.hpp", "document__core_8hpp.html", "document__core_8hpp" ],
    [ "index.hpp", "lib_2domain_2index_8hpp.html", null ],
    [ "org_data.hpp", "org__data_8hpp.html", [
      [ "org_data", "structorg__data.html", "structorg__data" ]
    ] ],
    [ "permissions.hpp", "permissions_8hpp.html", [
      [ "permission_level_weight", "structpermission__level__weight.html", "structpermission__level__weight" ],
      [ "key_weight", "structkey__weight.html", "structkey__weight" ],
      [ "wait_weight", "structwait__weight.html", "structwait__weight" ],
      [ "authority", "structauthority.html", "structauthority" ]
    ] ],
    [ "rammarket.hpp", "rammarket_8hpp.html", "rammarket_8hpp" ],
    [ "registrator_account_access.hpp", "registrator__account__access_8hpp.html", "registrator__account__access_8hpp" ],
    [ "table_balances_balances.hpp", "table__balances__balances_8hpp.html", "table__balances__balances_8hpp" ],
    [ "table_branch_branches.hpp", "table__branch__branches_8hpp.html", "table__branch__branches_8hpp" ],
    [ "table_branch_branchstat.hpp", "table__branch__branchstat_8hpp.html", "table__branch__branchstat_8hpp" ],
    [ "table_capital_debts.hpp", "table__capital__debts_8hpp.html", "table__capital__debts_8hpp" ],
    [ "table_counts.hpp", "table__counts_8hpp.html", "table__counts_8hpp" ],
    [ "table_draft_drafts.hpp", "table__draft__drafts_8hpp.html", "table__draft__drafts_8hpp" ],
    [ "table_draft_translations.hpp", "table__draft__translations_8hpp.html", "table__draft__translations_8hpp" ],
    [ "table_fund_accfunds.hpp", "table__fund__accfunds_8hpp.html", "table__fund__accfunds_8hpp" ],
    [ "table_fund_coopwallet.hpp", "table__fund__coopwallet_8hpp.html", "table__fund__coopwallet_8hpp" ],
    [ "table_fund_expfunds.hpp", "table__fund__expfunds_8hpp.html", "table__fund__expfunds_8hpp" ],
    [ "table_fund_fwithdraws.hpp", "table__fund__fwithdraws_8hpp.html", "table__fund__fwithdraws_8hpp" ],
    [ "table_gateway_incomes.hpp", "table__gateway__incomes_8hpp.html", "table__gateway__incomes_8hpp" ],
    [ "table_gateway_outcomes.hpp", "table__gateway__outcomes_8hpp.html", "table__gateway__outcomes_8hpp" ],
    [ "table_ledger_laccount.hpp", "table__ledger__laccount_8hpp.html", "table__ledger__laccount_8hpp" ],
    [ "table_ledger_writeoffs.hpp", "table__ledger__writeoffs_8hpp.html", "table__ledger__writeoffs_8hpp" ],
    [ "table_loan_debts.hpp", "table__loan__debts_8hpp.html", "table__loan__debts_8hpp" ],
    [ "table_loan_summaries.hpp", "table__loan__summaries_8hpp.html", "table__loan__summaries_8hpp" ],
    [ "table_marketplace_requests.hpp", "table__marketplace__requests_8hpp.html", "table__marketplace__requests_8hpp" ],
    [ "table_marketplace_segments.hpp", "table__marketplace__segments_8hpp.html", "table__marketplace__segments_8hpp" ],
    [ "table_marketplace_shipments.hpp", "table__marketplace__shipments_8hpp.html", "table__marketplace__shipments_8hpp" ],
    [ "table_registrator_accounts.hpp", "table__registrator__accounts_8hpp.html", "table__registrator__accounts_8hpp" ],
    [ "table_registrator_candidates.hpp", "table__registrator__candidates_8hpp.html", "table__registrator__candidates_8hpp" ],
    [ "table_registrator_candidates_legacy.hpp", "table__registrator__candidates__legacy_8hpp.html", "table__registrator__candidates__legacy_8hpp" ],
    [ "table_registrator_coops.hpp", "table__registrator__coops_8hpp.html", "table__registrator__coops_8hpp" ],
    [ "table_registrator_orgs.hpp", "table__registrator__orgs_8hpp.html", "table__registrator__orgs_8hpp" ],
    [ "table_registrator_verification.hpp", "table__registrator__verification_8hpp.html", [
      [ "verification", "structverification.html", "structverification" ]
    ] ],
    [ "table_soviet_addresses.hpp", "table__soviet__addresses_8hpp.html", "table__soviet__addresses_8hpp" ],
    [ "table_soviet_agreements.hpp", "table__soviet__agreements_8hpp.html", "table__soviet__agreements_8hpp" ],
    [ "table_soviet_agreements3.hpp", "table__soviet__agreements3_8hpp.html", "table__soviet__agreements3_8hpp" ],
    [ "table_soviet_approvals.hpp", "table__soviet__approvals_8hpp.html", "table__soviet__approvals_8hpp" ],
    [ "table_soviet_boards.hpp", "table__soviet__boards_8hpp.html", "table__soviet__boards_8hpp" ],
    [ "table_soviet_coagreements.hpp", "table__soviet__coagreements_8hpp.html", "table__soviet__coagreements_8hpp" ],
    [ "table_soviet_decisions.hpp", "table__soviet__decisions_8hpp.html", "table__soviet__decisions_8hpp" ],
    [ "table_soviet_participants.hpp", "table__soviet__participants_8hpp.html", "table__soviet__participants_8hpp" ],
    [ "table_soviet_programs.hpp", "table__soviet__programs_8hpp.html", "table__soviet__programs_8hpp" ],
    [ "table_soviet_progwallets.hpp", "table__soviet__progwallets_8hpp.html", "table__soviet__progwallets_8hpp" ],
    [ "table_soviet_staff.hpp", "table__soviet__staff_8hpp.html", "table__soviet__staff_8hpp" ],
    [ "table_wallet_deposits.hpp", "table__wallet__deposits_8hpp.html", "table__wallet__deposits_8hpp" ],
    [ "table_wallet_withdraws.hpp", "table__wallet__withdraws_8hpp.html", "table__wallet__withdraws_8hpp" ]
];