var dir_7a58a101592a95cebbfd07e6a75340e1 =
[
    [ "accounts.hpp", "accounts_8hpp.html", "accounts_8hpp" ],
    [ "admins.hpp", "admins_8hpp.html", "admins_8hpp" ],
    [ "agreements.hpp", "agreements_8hpp.html", "agreements_8hpp" ],
    [ "approves.hpp", "approves_8hpp.html", null ],
    [ "balances.hpp", "lib_2balances_8hpp.html", "lib_2balances_8hpp" ],
    [ "branch.hpp", "lib_2branch_8hpp.html", "lib_2branch_8hpp" ],
    [ "changes.hpp", "changes_8hpp.html", null ],
    [ "common.hpp", "common_8hpp.html", null ],
    [ "consts.hpp", "consts_8hpp.html", "consts_8hpp" ],
    [ "coops.hpp", "coops_8hpp.html", "coops_8hpp" ],
    [ "counts.hpp", "lib_2counts_8hpp.html", "lib_2counts_8hpp" ],
    [ "drafts.hpp", "drafts_8hpp.html", "drafts_8hpp" ],
    [ "funds.hpp", "funds_8hpp.html", "funds_8hpp" ],
    [ "permissions.hpp", "permissions_8hpp.html", [
      [ "permission_level_weight", "structpermission__level__weight.html", "structpermission__level__weight" ],
      [ "key_weight", "structkey__weight.html", "structkey__weight" ],
      [ "wait_weight", "structwait__weight.html", "structwait__weight" ],
      [ "authority", "structauthority.html", "structauthority" ]
    ] ],
    [ "programs.hpp", "programs_8hpp.html", "programs_8hpp" ],
    [ "rammarket.hpp", "rammarket_8hpp.html", "rammarket_8hpp" ],
    [ "registry.hpp", "registry_8hpp.html", "registry_8hpp" ],
    [ "shared_actions.hpp", "shared__actions_8hpp.html", "shared__actions_8hpp" ],
    [ "shared_approver.hpp", "shared__approver_8hpp.html", "shared__approver_8hpp" ],
    [ "shared_branch.hpp", "shared__branch_8hpp.html", "shared__branch_8hpp" ],
    [ "shared_debts.hpp", "shared__debts_8hpp.html", "shared__debts_8hpp" ],
    [ "shared_document.hpp", "shared__document_8hpp.html", "shared__document_8hpp" ],
    [ "shared_fund.hpp", "shared__fund_8hpp.html", null ],
    [ "shared_gateway.hpp", "shared__gateway_8hpp.html", "shared__gateway_8hpp" ],
    [ "shared_ledger.hpp", "shared__ledger_8hpp.html", "shared__ledger_8hpp" ],
    [ "shared_loan.hpp", "shared__loan_8hpp.html", "shared__loan_8hpp" ],
    [ "shared_marketplace.hpp", "shared__marketplace_8hpp.html", "shared__marketplace_8hpp" ],
    [ "shared_names.hpp", "shared__names_8hpp.html", "shared__names_8hpp" ],
    [ "shared_registrator.hpp", "shared__registrator_8hpp.html", "shared__registrator_8hpp" ],
    [ "shared_soviet.hpp", "shared__soviet_8hpp.html", "shared__soviet_8hpp" ],
    [ "shared_wallet.hpp", "shared__wallet_8hpp.html", "shared__wallet_8hpp" ],
    [ "utils.hpp", "utils_8hpp.html", "utils_8hpp" ]
];