var group__public__capital__processes =
[
    [ "Конфигурация контракта для кооператива", "group__public__capital__configuration__process.html", null ],
    [ "Выдача ссуды", "group__public__capital__debt__process.html", null ],
    [ "Фондирование членских взносов на программу", "group__public__capital__fundprog__process.html", null ],
    [ "Обновление кошелька программы", "group__public__capital__refresh__program__process.html", null ],
    [ "Возврат паевого взноса из программы", "group__public__capital__withdraw__from__program__process.html", null ],
    [ "Фондирование членских взносов на проект", "group__public__capital__fundproj__process.html", null ],
    [ "Обновления кошелька проекта", "group__public__capital__refresh__project__process.html", null ],
    [ "Возврат паевого взноса из проекта", "group__public__capital__withdraw__from__project__process.html", null ],
    [ "Списание расходов", "group__public__capital__create__expense__process.html", null ],
    [ "Расширение плана расходов", "group__public__capital__expand__expenses__process.html", null ],
    [ "Создание коммита", "group__public__capital__commit__creation__process.html", null ],
    [ "Обновления сегмента участника", "group__public__capital__segment__refresh__process.html", null ],
    [ "Регистрация доли вкладчика", "group__public__capital__share__registration__process.html", null ],
    [ "Аллокация программных инвестиций", "group__public__capital__allocate__process.html", null ],
    [ "Деаллокации программных инвестиций", "group__public__capital__diallocate__process.html", null ],
    [ "Инвестиции в программу", "group__public__capital__program__investment__process.html", null ],
    [ "Инвестиции в проект", "group__public__capital__project__investment__process.html", null ],
    [ "Возврат неиспользованных инвестиций", "group__public__capital__unused__return__process.html", null ],
    [ "Допуск к проекту", "group__public__capital__joining__process.html", null ],
    [ "Импорт вкладчиков", "group__public__capital__import__contributor__process.html", null ],
    [ "Регистрация вкладчиков", "group__public__capital__registration__process.html", null ],
    [ "Добавления соавтора проекта", "group__public__capital__add__author__process.html", null ],
    [ "Завершить голосование", "group__public__capital__voting__completion__process.html", null ],
    [ "Создать проект", "group__public__capital__project__creation__process.html", null ],
    [ "Удалить проект", "group__public__capital__project__deletion__process.html", null ],
    [ "Редактировать проект", "group__public__capital__project__editing__process.html", null ],
    [ "Открытие проекта для инвестиций", "group__public__capital__project__opening__process.html", null ],
    [ "Установить мастера проекта", "group__public__capital__set__master__process.html", null ],
    [ "Планирование проекта", "group__public__capital__planning__process.html", null ],
    [ "Запуска генерации проекта", "group__public__capital__project__start__process.html", null ],
    [ "Открыть голосование", "group__public__capital__voting__start__process.html", null ],
    [ "Приём имущественных взносов в программу", "group__public__capital__program__property__process.html", null ],
    [ "Приём имущественных взносов в проект", "group__public__capital__project__property__process.html", null ],
    [ "Конвертация взноса результатом", "group__public__capital__conversion__process.html", null ],
    [ "Внесение результата", "group__public__capital__result__process.html", null ],
    [ "Подсчет голосов по методу Водянова", "group__public__capital__calculate__votes__process.html", null ],
    [ "Голосование по методу Водянова", "group__public__capital__submit__vote__process.html", null ]
];