var hierarchy =
[
    [ "eosiobios::bios::abi_hash", "structeosiobios_1_1bios_1_1abi__hash.html", null ],
    [ "eosiosystem::abi_hash", "structeosiosystem_1_1abi__hash.html", null ],
    [ "accfund", "structaccfund.html", null ],
    [ "account", "structaccount.html", null ],
    [ "eosio::token::account", "structeosio_1_1token_1_1account.html", null ],
    [ "address", "structaddress.html", null ],
    [ "address_data", "structaddress__data.html", null ],
    [ "eosio::multisig::approval", "structeosio_1_1multisig_1_1approval.html", null ],
    [ "eosio::multisig::approvals_info", "structeosio_1_1multisig_1_1approvals__info.html", null ],
    [ "authority", "structauthority.html", null ],
    [ "eosiobios::authority", "structeosiobios_1_1authority.html", null ],
    [ "eosioboot::authority", "structeosioboot_1_1authority.html", null ],
    [ "eosiosystem::authority", "structeosiosystem_1_1authority.html", null ],
    [ "automator", "structautomator.html", null ],
    [ "autosigner", "structautosigner.html", null ],
    [ "balances_base", "structbalances__base.html", [
      [ "gateway::balances", "structgateway_1_1balances.html", null ],
      [ "marketplace::balances", "structmarketplace_1_1balances.html", null ],
      [ "registrator::balances", "structregistrator_1_1balances.html", null ]
    ] ],
    [ "eosiosystem::bid_refund", "structeosiosystem_1_1bid__refund.html", null ],
    [ "eosiosystem::block_info::block_batch_info", "structeosiosystem_1_1block__info_1_1block__batch__info.html", null ],
    [ "eosiobios::block_header", "structeosiobios_1_1block__header.html", null ],
    [ "eosiosystem::block_header", "structeosiosystem_1_1block__header.html", null ],
    [ "eosiosystem::block_info::block_info_record", "structeosiosystem_1_1block__info_1_1block__info__record.html", null ],
    [ "eosio::blockchain_parameters", null, [
      [ "eosiosystem::eosio_global_state", "structeosiosystem_1_1eosio__global__state.html", null ]
    ] ],
    [ "board_member", "structboard__member.html", null ],
    [ "boards", "structboards.html", null ],
    [ "branch", "structbranch.html", null ],
    [ "changes", "structchanges.html", null ],
    [ "eosiosystem::exchange_state::connector", "structeosiosystem_1_1exchange__state_1_1connector.html", null ],
    [ "contract", null, [
      [ "eosio::multisig", "classeosio_1_1multisig.html", null ],
      [ "eosio::token", "classeosio_1_1token.html", null ],
      [ "eosio::wrap", "classeosio_1_1wrap.html", null ]
    ] ],
    [ "eosio::contract", null, [
      [ "eosiobios::bios", "classeosiobios_1_1bios.html", null ],
      [ "eosioboot::boot", "classeosioboot_1_1boot.html", null ],
      [ "eosiosystem::native", "classeosiosystem_1_1native.html", [
        [ "eosiosystem::system_contract", "classeosiosystem_1_1system__contract.html", null ]
      ] ],
      [ "fund", "classfund.html", null ],
      [ "gateway", "classgateway.html", null ],
      [ "marketplace", "classmarketplace.html", null ],
      [ "registrator", "classregistrator.html", null ],
      [ "sendinline", "classsendinline.html", null ],
      [ "soviet", "classsoviet.html", null ]
    ] ],
    [ "eosio::testing::contracts", "structeosio_1_1testing_1_1contracts.html", null ],
    [ "cooperative", "structcooperative.html", null ],
    [ "counts_base", "structcounts__base.html", [
      [ "counts", "structcounts.html", null ],
      [ "fund::counts", "structfund_1_1counts.html", null ],
      [ "gateway::counts", "structgateway_1_1counts.html", null ],
      [ "marketplace::counts", "structmarketplace_1_1counts.html", null ]
    ] ],
    [ "eosio::token::currency_stats", "structeosio_1_1token_1_1currency__stats.html", null ],
    [ "decision", "structdecision.html", null ],
    [ "eosiosystem::delegated_bandwidth", "structeosiosystem_1_1delegated__bandwidth.html", null ],
    [ "document", "structdocument.html", null ],
    [ "eosiosystem::emission_state", "structeosiosystem_1_1emission__state.html", null ],
    [ "exchange_params", "structexchange__params.html", null ],
    [ "eosiosystem::exchange_state", "structeosiosystem_1_1exchange__state.html", null ],
    [ "expfund", "structexpfund.html", null ],
    [ "fundwallet", "structfundwallet.html", null ],
    [ "fwithdraw", "structfwithdraw.html", null ],
    [ "system_contracts::testing::test_contracts::blockinfo_tester::get_latest_block_batch_info", "structsystem__contracts_1_1testing_1_1test__contracts_1_1blockinfo__tester_1_1get__latest__block__batch__info.html", null ],
    [ "eosio::multisig::invalidation", "structeosio_1_1multisig_1_1invalidation.html", null ],
    [ "joincoops", "structjoincoops.html", null ],
    [ "eosiobios::key_weight", "structeosiobios_1_1key__weight.html", null ],
    [ "eosioboot::key_weight", "structeosioboot_1_1key__weight.html", null ],
    [ "eosiosystem::key_weight", "structeosiosystem_1_1key__weight.html", null ],
    [ "key_weight", "structkey__weight.html", null ],
    [ "eosiosystem::block_info::latest_block_batch_info_result", "structeosiosystem_1_1block__info_1_1latest__block__batch__info__result.html", null ],
    [ "system_contracts::testing::test_contracts::blockinfo_tester::latest_block_batch_info_result", "structsystem__contracts_1_1testing_1_1test__contracts_1_1blockinfo__tester_1_1latest__block__batch__info__result.html", null ],
    [ "eosiosystem::limit_auth_change", "structeosiosystem_1_1limit__auth__change.html", null ],
    [ "eosiosystem::name_bid", "structeosiosystem_1_1name__bid.html", null ],
    [ "eosio::multisig::old_approvals_info", "structeosio_1_1multisig_1_1old__approvals__info.html", null ],
    [ "onedeposit", "structonedeposit.html", null ],
    [ "onedraft", "structonedraft.html", null ],
    [ "onewallet", "structonewallet.html", null ],
    [ "onewithdraw", "structonewithdraw.html", null ],
    [ "org_data", "structorg__data.html", null ],
    [ "participant", "structparticipant.html", null ],
    [ "eosiobios::permission_level_weight", "structeosiobios_1_1permission__level__weight.html", null ],
    [ "eosioboot::permission_level_weight", "structeosioboot_1_1permission__level__weight.html", null ],
    [ "eosiosystem::permission_level_weight", "structeosiosystem_1_1permission__level__weight.html", null ],
    [ "permission_level_weight", "structpermission__level__weight.html", null ],
    [ "eosiosystem::powerup_config", "structeosiosystem_1_1powerup__config.html", null ],
    [ "eosiosystem::powerup_order", "structeosiosystem_1_1powerup__order.html", null ],
    [ "eosiosystem::powerup_state", "structeosiosystem_1_1powerup__state.html", null ],
    [ "eosiosystem::powerup_state_resource", "structeosiosystem_1_1powerup__state__resource.html", null ],
    [ "eosiosystem::producer_info", "structeosiosystem_1_1producer__info.html", null ],
    [ "progcomarket", "structprogcomarket.html", null ],
    [ "progwallet", "structprogwallet.html", null ],
    [ "eosio::multisig::proposal", "structeosio_1_1multisig_1_1proposal.html", null ],
    [ "eosiosystem::ram_debt_record", "structeosiosystem_1_1ram__debt__record.html", null ],
    [ "eosiosystem::refund_request", "structeosiosystem_1_1refund__request.html", null ],
    [ "request", "structrequest.html", null ],
    [ "right", "structright.html", null ],
    [ "staff", "structstaff.html", null ],
    [ "translation", "structtranslation.html", null ],
    [ "eosiosystem::user_resources", "structeosiosystem_1_1user__resources.html", null ],
    [ "eosio::testing::contracts::util", "structeosio_1_1testing_1_1contracts_1_1util.html", null ],
    [ "verification", "structverification.html", null ],
    [ "eosiosystem::voter_info", "structeosiosystem_1_1voter__info.html", null ],
    [ "eosiobios::wait_weight", "structeosiobios_1_1wait__weight.html", null ],
    [ "eosioboot::wait_weight", "structeosioboot_1_1wait__weight.html", null ],
    [ "eosiosystem::wait_weight", "structeosiosystem_1_1wait__weight.html", null ],
    [ "wait_weight", "structwait__weight.html", null ]
];