var hierarchy =
[
    [ "_abi_hash", "struct__abi__hash.html", null ],
    [ "eosiobios::bios::abi_hash", "structeosiobios_1_1bios_1_1abi__hash.html", null ],
    [ "eosiosystem::abi_hash", "structeosiosystem_1_1abi__hash.html", null ],
    [ "accfund", "structaccfund.html", null ],
    [ "account", "structaccount.html", null ],
    [ "eosio::token::account", "structeosio_1_1token_1_1account.html", null ],
    [ "powerup_tester::account_info", "structpowerup__tester_1_1account__info.html", null ],
    [ "Ledger::accounts", "struct_ledger_1_1accounts.html", null ],
    [ "address", "structaddress.html", null ],
    [ "address_data", "structaddress__data.html", null ],
    [ "agreement", "structagreement.html", null ],
    [ "agreement2", "structagreement2.html", null ],
    [ "Capital::appendix", "struct_capital_1_1appendix.html", null ],
    [ "Approver::approval", "struct_approver_1_1approval.html", null ],
    [ "eosio::multisig::approval", "structeosio_1_1multisig_1_1approval.html", null ],
    [ "eosio::multisig::approvals_info", "structeosio_1_1multisig_1_1approvals__info.html", null ],
    [ "authority", "structauthority.html", null ],
    [ "eosiobios::authority", "structeosiobios_1_1authority.html", null ],
    [ "eosioboot::authority", "structeosioboot_1_1authority.html", null ],
    [ "eosiosystem::authority", "structeosiosystem_1_1authority.html", null ],
    [ "automator", "structautomator.html", null ],
    [ "autosigner", "structautosigner.html", null ],
    [ "balances_base", "structbalances__base.html", [
      [ "marketplace::balances", "structmarketplace_1_1balances.html", null ]
    ] ],
    [ "eosiosystem::bid_refund", "structeosiosystem_1_1bid__refund.html", null ],
    [ "eosiosystem::block_info::block_batch_info", "structeosiosystem_1_1block__info_1_1block__batch__info.html", null ],
    [ "eosiobios::block_header", "structeosiobios_1_1block__header.html", null ],
    [ "eosiosystem::block_header", "structeosiosystem_1_1block__header.html", null ],
    [ "anonymous_namespace{eosio.system_blockinfo_tests.cpp}::block_info_record", "structanonymous__namespace_02eosio_8system__blockinfo__tests_8cpp_03_1_1block__info__record.html", null ],
    [ "eosiosystem::block_info::block_info_record", "structeosiosystem_1_1block__info_1_1block__info__record.html", null ],
    [ "eosio::blockchain_parameters", null, [
      [ "eosiosystem::eosio_global_state", "structeosiosystem_1_1eosio__global__state.html", null ]
    ] ],
    [ "board_member", "structboard__member.html", null ],
    [ "boards", "structboards.html", null ],
    [ "branchstat", "structbranchstat.html", null ],
    [ "Registrator::candidate", "struct_registrator_1_1candidate.html", null ],
    [ "Registrator::candidate_legacy", "struct_registrator_1_1candidate__legacy.html", null ],
    [ "Capital::capital_wallet", "struct_capital_1_1capital__wallet.html", null ],
    [ "changes", "structchanges.html", null ],
    [ "coagreement", "structcoagreement.html", null ],
    [ "Capital::Commits::commit", "struct_capital_1_1_commits_1_1commit.html", null ],
    [ "Capital::config", "struct_capital_1_1config.html", null ],
    [ "connector", "structconnector.html", null ],
    [ "eosiosystem::exchange_state::connector", "structeosiosystem_1_1exchange__state_1_1connector.html", null ],
    [ "eosio::contract", null, [
      [ "branch", "classbranch.html", null ],
      [ "capital", "classcapital.html", null ],
      [ "contributor", "classcontributor.html", null ],
      [ "draft", "classdraft.html", null ],
      [ "eosio::multisig", "classeosio_1_1multisig.html", null ],
      [ "eosio::token", "classeosio_1_1token.html", null ],
      [ "eosio::wrap", "classeosio_1_1wrap.html", null ],
      [ "eosiobios::bios", "classeosiobios_1_1bios.html", null ],
      [ "eosioboot::boot", "classeosioboot_1_1boot.html", null ],
      [ "eosiosystem::native", "classeosiosystem_1_1native.html", [
        [ "eosiosystem::system_contract", "classeosiosystem_1_1system__contract.html", null ]
      ] ],
      [ "fund", "classfund.html", null ],
      [ "gateway", "classgateway.html", null ],
      [ "ledger", "classledger.html", null ],
      [ "loan", "classloan.html", null ],
      [ "marketplace", "classmarketplace.html", null ],
      [ "meet", "classmeet.html", null ],
      [ "registrator", "classregistrator.html", null ],
      [ "sendinline", "classsendinline.html", null ],
      [ "soviet", "classsoviet.html", null ],
      [ "starter", "classstarter.html", null ],
      [ "test", "classtest.html", null ],
      [ "wallet", "classwallet.html", null ]
    ] ],
    [ "Capital::contributor", "struct_capital_1_1contributor.html", null ],
    [ "coobranch", "structcoobranch.html", null ],
    [ "cooperative", "structcooperative.html", null ],
    [ "cooperative2", "structcooperative2.html", null ],
    [ "coopwallet", "structcoopwallet.html", null ],
    [ "core_sym", "structcore__sym.html", null ],
    [ "counts_base", "structcounts__base.html", [
      [ "counts", "structcounts.html", null ],
      [ "draft::counts", "structdraft_1_1counts.html", null ],
      [ "fund::counts", "structfund_1_1counts.html", null ],
      [ "marketplace::counts", "structmarketplace_1_1counts.html", null ]
    ] ],
    [ "counts_data", "structcounts__data.html", null ],
    [ "Capital::crps_data", "struct_capital_1_1crps__data.html", null ],
    [ "eosio::token::currency_stats", "structeosio_1_1token_1_1currency__stats.html", null ],
    [ "Capital::Debts::debt", "struct_capital_1_1_debts_1_1debt.html", null ],
    [ "debt", "structdebt.html", null ],
    [ "Loan::debt", "struct_loan_1_1debt.html", null ],
    [ "decision", "structdecision.html", null ],
    [ "eosiosystem::delegated_bandwidth", "structeosiosystem_1_1delegated__bandwidth.html", null ],
    [ "Wallet::deposit", "struct_wallet_1_1deposit.html", null ],
    [ "document", "structdocument.html", null ],
    [ "document2", "structdocument2.html", null ],
    [ "eosiosystem::emission_state", "structeosiosystem_1_1emission__state.html", null ],
    [ "eosio_system_tester", null, [
      [ "powerup_tester", "structpowerup__tester.html", null ]
    ] ],
    [ "eosiosystem::exchange_state", "structeosiosystem_1_1exchange__state.html", null ],
    [ "Capital::expense", "struct_capital_1_1expense.html", null ],
    [ "expfund", "structexpfund.html", null ],
    [ "Capital::fact_pool", "struct_capital_1_1fact__pool.html", null ],
    [ "fwithdraw", "structfwithdraw.html", null ],
    [ "Capital::generation_amounts", "struct_capital_1_1generation__amounts.html", null ],
    [ "system_contracts::testing::test_contracts::blockinfo_tester::get_latest_block_batch_info", "structsystem__contracts_1_1testing_1_1test__contracts_1_1blockinfo__tester_1_1get__latest__block__batch__info.html", null ],
    [ "Capital::global_state", "struct_capital_1_1global__state.html", null ],
    [ "contributor::global_state", "structcontributor_1_1global__state.html", null ],
    [ "Gateway::income", "struct_gateway_1_1income.html", null ],
    [ "eosio::multisig::invalidation", "structeosio_1_1multisig_1_1invalidation.html", null ],
    [ "Capital::invest", "struct_capital_1_1invest.html", null ],
    [ "joincoops", "structjoincoops.html", null ],
    [ "eosiobios::key_weight", "structeosiobios_1_1key__weight.html", null ],
    [ "eosioboot::key_weight", "structeosioboot_1_1key__weight.html", null ],
    [ "eosiosystem::key_weight", "structeosiosystem_1_1key__weight.html", null ],
    [ "key_weight", "structkey__weight.html", null ],
    [ "laccount", "structlaccount.html", null ],
    [ "eosiosystem::block_info::latest_block_batch_info_result", "structeosiosystem_1_1block__info_1_1latest__block__batch__info__result.html", null ],
    [ "system_contracts::testing::test_contracts::blockinfo_tester::latest_block_batch_info_result", "structsystem__contracts_1_1testing_1_1test__contracts_1_1blockinfo__tester_1_1latest__block__batch__info__result.html", null ],
    [ "Ledger", "class_ledger.html", null ],
    [ "eosiosystem::limit_auth_change", "structeosiosystem_1_1limit__auth__change.html", null ],
    [ "Meet::meet", "struct_meet_1_1meet.html", null ],
    [ "meet_point", "structmeet__point.html", null ],
    [ "membership_crps", "structmembership__crps.html", null ],
    [ "eosiosystem::name_bid", "structeosiosystem_1_1name__bid.html", null ],
    [ "Document::named_document", "struct_document_1_1named__document.html", null ],
    [ "eosio::multisig::old_approvals_info", "structeosio_1_1multisig_1_1old__approvals__info.html", null ],
    [ "onedraft", "structonedraft.html", null ],
    [ "org_data", "structorg__data.html", null ],
    [ "Gateway::outcome", "struct_gateway_1_1outcome.html", null ],
    [ "contributor::participant", "structcontributor_1_1participant.html", null ],
    [ "participant", "structparticipant.html", null ],
    [ "eosiobios::permission_level_weight", "structeosiobios_1_1permission__level__weight.html", null ],
    [ "eosioboot::permission_level_weight", "structeosioboot_1_1permission__level__weight.html", null ],
    [ "eosiosystem::permission_level_weight", "structeosiosystem_1_1permission__level__weight.html", null ],
    [ "permission_level_weight", "structpermission__level__weight.html", null ],
    [ "Capital::plan_pool", "struct_capital_1_1plan__pool.html", null ],
    [ "eosiosystem::powerup_config", "structeosiosystem_1_1powerup__config.html", null ],
    [ "powerup_config", "structpowerup__config.html", null ],
    [ "eosiosystem::powerup_order", "structeosiosystem_1_1powerup__order.html", null ],
    [ "eosiosystem::powerup_state", "structeosiosystem_1_1powerup__state.html", null ],
    [ "eosiosystem::powerup_state_resource", "structeosiosystem_1_1powerup__state__resource.html", null ],
    [ "eosiosystem::producer_info", "structeosiosystem_1_1producer__info.html", null ],
    [ "program", "structprogram.html", null ],
    [ "Capital::program_invest", "struct_capital_1_1program__invest.html", null ],
    [ "Capital::ProgramProperties::program_property", "struct_capital_1_1_program_properties_1_1program__property.html", null ],
    [ "Capital::program_withdraw", "struct_capital_1_1program__withdraw.html", null ],
    [ "ProgramInfo", "struct_program_info.html", null ],
    [ "progwallet", "structprogwallet.html", null ],
    [ "Capital::project", "struct_capital_1_1project.html", null ],
    [ "Capital::project_wallet", "struct_capital_1_1project__wallet.html", null ],
    [ "Capital::project_withdraw", "struct_capital_1_1project__withdraw.html", null ],
    [ "Capital::ProjectProperties::property", "struct_capital_1_1_project_properties_1_1property.html", null ],
    [ "eosio::multisig::proposal", "structeosio_1_1multisig_1_1proposal.html", null ],
    [ "Meet::question", "struct_meet_1_1question.html", null ],
    [ "question_result", "structquestion__result.html", null ],
    [ "eosiosystem::ram_debt_record", "structeosiosystem_1_1ram__debt__record.html", null ],
    [ "eosiosystem::refund_request", "structeosiosystem_1_1refund__request.html", null ],
    [ "Marketplace::request", "struct_marketplace_1_1request.html", null ],
    [ "Capital::result", "struct_capital_1_1result.html", null ],
    [ "right", "structright.html", null ],
    [ "Capital::Segments::segment", "struct_capital_1_1_segments_1_1segment.html", null ],
    [ "Marketplace::segment", "struct_marketplace_1_1segment.html", null ],
    [ "Marketplace::shipment", "struct_marketplace_1_1shipment.html", null ],
    [ "signature_info", "structsignature__info.html", null ],
    [ "simple_wallet", "structsimple__wallet.html", null ],
    [ "staff", "structstaff.html", null ],
    [ "Loan::summary", "struct_loan_1_1summary.html", null ],
    [ "tester", null, [
      [ "eosio_msig_tester", "classeosio__msig__tester.html", null ],
      [ "eosio_token_tester", "classeosio__token__tester.html", null ],
      [ "eosio_wrap_tester", "classeosio__wrap__tester.html", null ]
    ] ],
    [ "TESTER", null, [
      [ "eosio_system::eosio_system_tester", "classeosio__system_1_1eosio__system__tester.html", [
        [ "coopenomics_tester", "classcoopenomics__tester.html", [
          [ "fund_tester", "structfund__tester.html", null ]
        ] ],
        [ "limitauth_tester", "structlimitauth__tester.html", null ]
      ] ]
    ] ],
    [ "test::testrecord", "structtest_1_1testrecord.html", null ],
    [ "translation", "structtranslation.html", null ],
    [ "eosiosystem::user_resources", "structeosiosystem_1_1user__resources.html", null ],
    [ "verification", "structverification.html", null ],
    [ "Capital::vote", "struct_capital_1_1vote.html", null ],
    [ "Capital::vote_input", "struct_capital_1_1vote__input.html", null ],
    [ "vote_point", "structvote__point.html", null ],
    [ "eosiosystem::voter_info", "structeosiosystem_1_1voter__info.html", null ],
    [ "Capital::voting_amounts", "struct_capital_1_1voting__amounts.html", null ],
    [ "Capital::voting_data", "struct_capital_1_1voting__data.html", null ],
    [ "eosiobios::wait_weight", "structeosiobios_1_1wait__weight.html", null ],
    [ "eosioboot::wait_weight", "structeosioboot_1_1wait__weight.html", null ],
    [ "eosiosystem::wait_weight", "structeosiosystem_1_1wait__weight.html", null ],
    [ "wait_weight", "structwait__weight.html", null ],
    [ "Wallet", "class_wallet.html", null ],
    [ "Wallet::withdraw", "struct_wallet_1_1withdraw.html", null ],
    [ "contributor::withdrawal_request", "structcontributor_1_1withdrawal__request.html", null ],
    [ "writeoff_op", "structwriteoff__op.html", null ]
];